insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('host-1930', '¿En qué país (o países) se disputó el Mundial 1930?', '["Uruguay","Argentina","Italia","Brasil"]'::jsonb, 0, 'medium', 1930, 'sedes'),
('host-1934', '¿En qué país (o países) se disputó el Mundial 1934?', '["Italia","Francia","Alemania","España"]'::jsonb, 0, 'medium', 1934, 'sedes'),
('host-1938', '¿En qué país (o países) se disputó el Mundial 1938?', '["Francia","Italia","Suiza","Bélgica"]'::jsonb, 0, 'medium', 1938, 'sedes'),
('host-1950', '¿En qué país (o países) se disputó el Mundial 1950?', '["Brasil","Uruguay","Chile","Argentina"]'::jsonb, 0, 'medium', 1950, 'sedes'),
('host-1954', '¿En qué país (o países) se disputó el Mundial 1954?', '["Suiza","Alemania","Austria","Suecia"]'::jsonb, 0, 'medium', 1954, 'sedes'),
('host-1958', '¿En qué país (o países) se disputó el Mundial 1958?', '["Suecia","Noruega","Dinamarca","Finlandia"]'::jsonb, 0, 'medium', 1958, 'sedes'),
('host-1962', '¿En qué país (o países) se disputó el Mundial 1962?', '["Chile","Argentina","Perú","Colombia"]'::jsonb, 0, 'medium', 1962, 'sedes'),
('host-1966', '¿En qué país (o países) se disputó el Mundial 1966?', '["Inglaterra","Escocia","Irlanda","Gales"]'::jsonb, 0, 'medium', 1966, 'sedes'),
('host-1970', '¿En qué país (o países) se disputó el Mundial 1970?', '["México","Estados Unidos","Colombia","Cuba"]'::jsonb, 0, 'medium', 1970, 'sedes'),
('host-1974', '¿En qué país (o países) se disputó el Mundial 1974?', '["Alemania Occidental","Austria","Suiza","Países Bajos"]'::jsonb, 0, 'medium', 1974, 'sedes'),
('host-1978', '¿En qué país (o países) se disputó el Mundial 1978?', '["Argentina","Uruguay","Chile","Brasil"]'::jsonb, 0, 'medium', 1978, 'sedes'),
('host-1982', '¿En qué país (o países) se disputó el Mundial 1982?', '["España","Portugal","Italia","Francia"]'::jsonb, 0, 'medium', 1982, 'sedes'),
('host-1986', '¿En qué país (o países) se disputó el Mundial 1986?', '["México","Estados Unidos","Colombia","Brasil"]'::jsonb, 0, 'medium', 1986, 'sedes'),
('host-1990', '¿En qué país (o países) se disputó el Mundial 1990?', '["Italia","Francia","Alemania","España"]'::jsonb, 0, 'medium', 1990, 'sedes'),
('host-1994', '¿En qué país (o países) se disputó el Mundial 1994?', '["Estados Unidos","México","Canadá","Brasil"]'::jsonb, 0, 'medium', 1994, 'sedes'),
('host-1998', '¿En qué país (o países) se disputó el Mundial 1998?', '["Francia","Bélgica","Alemania","España"]'::jsonb, 0, 'medium', 1998, 'sedes'),
('host-2002', '¿En qué país (o países) se disputó el Mundial 2002?', '["Corea del Sur y Japón","China","Tailandia","Australia"]'::jsonb, 0, 'medium', 2002, 'sedes'),
('host-2006', '¿En qué país (o países) se disputó el Mundial 2006?', '["Alemania","Austria","Suiza","Polonia"]'::jsonb, 0, 'medium', 2006, 'sedes'),
('host-2010', '¿En qué país (o países) se disputó el Mundial 2010?', '["Sudáfrica","Nigeria","Egipto","Marruecos"]'::jsonb, 0, 'easy', 2010, 'sedes'),
('host-2014', '¿En qué país (o países) se disputó el Mundial 2014?', '["Brasil","Argentina","Chile","Colombia"]'::jsonb, 0, 'easy', 2014, 'sedes'),
('host-2018', '¿En qué país (o países) se disputó el Mundial 2018?', '["Rusia","Ucrania","Polonia","Turquía"]'::jsonb, 0, 'easy', 2018, 'sedes'),
('host-2022', '¿En qué país (o países) se disputó el Mundial 2022?', '["Qatar","Emiratos Árabes","Arabia Saudita","Baréin"]'::jsonb, 0, 'easy', 2022, 'sedes'),
('champ-1930', '¿Qué selección ganó el Mundial 1930?', '["Uruguay","Argentina","Brasil","Italia"]'::jsonb, 0, 'medium', 1930, 'campeones'),
('champ-1934', '¿Qué selección ganó el Mundial 1934?', '["Italia","Checoslovaquia","Alemania","Austria"]'::jsonb, 0, 'medium', 1934, 'campeones'),
('champ-1938', '¿Qué selección ganó el Mundial 1938?', '["Italia","Hungría","Brasil","Suecia"]'::jsonb, 0, 'medium', 1938, 'campeones'),
('champ-1950', '¿Qué selección ganó el Mundial 1950?', '["Uruguay","Brasil","Suecia","España"]'::jsonb, 0, 'medium', 1950, 'campeones'),
('champ-1954', '¿Qué selección ganó el Mundial 1954?', '["Alemania Occidental","Hungría","Austria","Uruguay"]'::jsonb, 0, 'medium', 1954, 'campeones'),
('champ-1958', '¿Qué selección ganó el Mundial 1958?', '["Brasil","Suecia","Francia","Alemania"]'::jsonb, 0, 'medium', 1958, 'campeones'),
('champ-1962', '¿Qué selección ganó el Mundial 1962?', '["Brasil","Checoslovaquia","Chile","Yugoslavia"]'::jsonb, 0, 'medium', 1962, 'campeones'),
('champ-1966', '¿Qué selección ganó el Mundial 1966?', '["Inglaterra","Alemania","Portugal","Argentina"]'::jsonb, 0, 'medium', 1966, 'campeones'),
('champ-1970', '¿Qué selección ganó el Mundial 1970?', '["Brasil","Italia","Alemania","Uruguay"]'::jsonb, 0, 'medium', 1970, 'campeones'),
('champ-1974', '¿Qué selección ganó el Mundial 1974?', '["Alemania Occidental","Países Bajos","Polonia","Brasil"]'::jsonb, 0, 'medium', 1974, 'campeones'),
('champ-1978', '¿Qué selección ganó el Mundial 1978?', '["Argentina","Países Bajos","Brasil","Italia"]'::jsonb, 0, 'medium', 1978, 'campeones'),
('champ-1982', '¿Qué selección ganó el Mundial 1982?', '["Italia","Alemania","Francia","Polonia"]'::jsonb, 0, 'medium', 1982, 'campeones'),
('champ-1986', '¿Qué selección ganó el Mundial 1986?', '["Argentina","Alemania","Francia","Bélgica"]'::jsonb, 0, 'medium', 1986, 'campeones'),
('champ-1990', '¿Qué selección ganó el Mundial 1990?', '["Alemania Occidental","Argentina","Italia","Inglaterra"]'::jsonb, 0, 'medium', 1990, 'campeones'),
('champ-1994', '¿Qué selección ganó el Mundial 1994?', '["Brasil","Italia","Suecia","Bulgaria"]'::jsonb, 0, 'medium', 1994, 'campeones'),
('champ-1998', '¿Qué selección ganó el Mundial 1998?', '["Francia","Brasil","Croacia","Países Bajos"]'::jsonb, 0, 'medium', 1998, 'campeones'),
('champ-2002', '¿Qué selección ganó el Mundial 2002?', '["Brasil","Alemania","Turquía","Corea del Sur"]'::jsonb, 0, 'medium', 2002, 'campeones'),
('champ-2006', '¿Qué selección ganó el Mundial 2006?', '["Italia","Francia","Alemania","Portugal"]'::jsonb, 0, 'easy', 2006, 'campeones')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;