insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('x-42', '¿Senegal sorprendió al campeón Francia en el arranque de…?', '["2002","2010","2018","2006"]'::jsonb, 0, 'medium', 2002, 'momentos'),
('x-43', '¿Italia quedó fuera en fase de grupos siendo campeón defensor en…?', '["2010","2006","2014","2018"]'::jsonb, 0, 'hard', 2010, 'momentos'),
('x-44', '¿España quedó campeona defensora eliminada temprano en…?', '["2014","2010","2018","2022"]'::jsonb, 0, 'medium', 2014, 'momentos'),
('x-45', '¿Alemania campeona cayó en fase de grupos en…?', '["2018","2014","2022","2010"]'::jsonb, 0, 'medium', 2018, 'momentos'),
('x-46', '¿El primer Mundial transmitido en color en TV fue en…?', '["1970","1966","1974","1982"]'::jsonb, 0, 'hard', 1970, 'curiosidades'),
('x-47', '¿El "Grupo de la muerte" suele referirse a grupos muy competitivos; en 2014 uno incluía a Alemania, Portugal, Ghana y…?', '["Estados Unidos","España","Italia","Uruguay"]'::jsonb, 0, 'hard', 2014, 'formato'),
('x-48', '¿Qué anfitrión cayó 7-1 ante Alemania en semifinales en 2014?', '["Brasil","Sudáfrica","Rusia","Japón"]'::jsonb, 0, 'easy', 2014, 'momentos'),
('x-49', '¿Miroslav Klose marcó goles en cuántos Mundiales distintos?', '["4","3","5","2"]'::jsonb, 0, 'hard', null, 'goleadores'),
('x-50', '¿Cristiano Ronaldo marcó su primer gol mundialista en…?', '["2006","2010","2014","2002"]'::jsonb, 0, 'medium', 2006, 'leyendas'),
('y-01', '¿Quién fue el máximo goleador del Mundial 2002?', '["Ronaldo","Rivaldo","Klose","Henry"]'::jsonb, 0, 'medium', 2002, 'goleadores'),
('y-02', '¿Quién ganó el Balón de Oro del Mundial 2010?', '["Diego Forlán","Iniesta","Sneijder","Xavi"]'::jsonb, 0, 'hard', 2010, 'premios'),
('y-03', '¿Cuántos goles marcó Just Fontaine en un solo Mundial?', '["13","10","11","15"]'::jsonb, 0, 'hard', 1958, 'records'),
('y-04', '¿En qué Mundial debutó el VAR en partidos oficiales?', '["2018","2014","2022","2010"]'::jsonb, 0, 'medium', 2018, 'formato'),
('y-05', '¿Qué selección ganó el Mundial 1958?', '["Brasil","Suecia","Francia","Alemania"]'::jsonb, 0, 'easy', 1958, 'campeones'),
('y-06', '¿Qué país organizó el Mundial 1974?', '["Alemania Occidental","Holanda","Argentina","México"]'::jsonb, 0, 'medium', 1974, 'sedes'),
('y-07', '¿Quién marcó el gol de la "Mano de Dios"?', '["Maradona","Valdano","Burruchaga","Caniggia"]'::jsonb, 0, 'easy', 1986, 'momentos'),
('y-08', '¿Qué selección eliminó a Brasil en cuartos en 1998?', '["Francia","Holanda","Dinamarca","Italia"]'::jsonb, 0, 'medium', 1998, 'momentos'),
('y-09', '¿Cuántas Copas del Mundo ganó Pelé como jugador?', '["3","2","4","1"]'::jsonb, 0, 'medium', null, 'leyendas'),
('y-10', '¿En qué año Uruguay ganó su segunda Copa del Mundo?', '["1950","1930","1966","1970"]'::jsonb, 0, 'medium', 1950, 'campeones'),
('y-11', '¿Quién fue entrenador de España en el Mundial 2010?', '["Del Bosque","Aragonés","Lopetegui","Enrique"]'::jsonb, 0, 'medium', 2010, 'selecciones'),
('y-12', '¿Qué país fue sede del Mundial 2002 junto a Corea del Sur?', '["Japón","China","Tailandia","Singapur"]'::jsonb, 0, 'easy', 2002, 'sedes'),
('y-13', '¿Quién marcó el gol del 2-1 en la final 2014?', '["Götze","Schürrle","Kroos","Müller"]'::jsonb, 0, 'medium', 2014, 'finales'),
('y-14', '¿Qué selección ganó el Mundial 1966?', '["Inglaterra","Alemania","Portugal","URSS"]'::jsonb, 0, 'easy', 1966, 'campeones'),
('y-15', '¿Cuántos equipos participaron en el Mundial 1982?', '["24","16","32","20"]'::jsonb, 0, 'hard', 1982, 'formato'),
('y-16', '¿Quién fue el arquero de Argentina en la final 2022?', '["Martínez","Romero","Armani","Musso"]'::jsonb, 0, 'easy', 2022, 'selecciones'),
('y-17', '¿Qué país africano llegó a semifinales en 2022?', '["Marruecos","Senegal","Camerún","Ghana"]'::jsonb, 0, 'easy', 2022, 'records'),
('y-18', '¿En qué Mundial Zidane cabeceó a Materazzi y fue expulsado?', '["2006","2002","1998","2010"]'::jsonb, 0, 'easy', 2006, 'momentos'),
('y-19', '¿Quién ganó el Mundial 1978?', '["Argentina","Holanda","Brasil","Italia"]'::jsonb, 0, 'easy', 1978, 'campeones'),
('y-20', '¿Qué selección ganó el Mundial 1934?', '["Italia","Checoslovaquia","Alemania","Austria"]'::jsonb, 0, 'hard', 1934, 'campeones'),
('y-21', '¿Cuántos Mundiales ganó Alemania (incl. Alemania Occidental)?', '["4","3","5","2"]'::jsonb, 0, 'medium', null, 'campeones'),
('y-22', '¿Quién marcó el primer gol en la historia de los Mundiales?', '["Lucien Laurent","Pelé","Stábile","Meazza"]'::jsonb, 0, 'hard', 1930, 'records'),
('y-23', '¿Qué país organizó el Mundial 1994?', '["Estados Unidos","México","Brasil","Canadá"]'::jsonb, 0, 'easy', 1994, 'sedes'),
('y-24', '¿Quién fue el goleador del Mundial 1986 con 6 goles?', '["Lineker","Maradona","Butragueño","Careca"]'::jsonb, 0, 'hard', 1986, 'goleadores'),
('y-25', '¿En qué Mundial se usó por primera vez la tanda de penales en final?', '["1994","1986","1990","1998"]'::jsonb, 0, 'hard', 1994, 'finales'),
('y-26', '¿Qué selección ganó el Mundial 1982?', '["Italia","Alemania","Brasil","Francia"]'::jsonb, 0, 'medium', 1982, 'campeones'),
('y-27', '¿Quién marcó el hat-trick de España en el 7-0 a Costa Rica en 2022?', '["Ferran Torres","Morata","Olmo","Asensio"]'::jsonb, 0, 'medium', 2022, 'momentos'),
('y-28', '¿Qué país fue campeón en 1990?', '["Alemania Occidental","Argentina","Italia","Inglaterra"]'::jsonb, 0, 'medium', 1990, 'campeones'),
('y-29', '¿Cuántos goles marcó James Rodríguez en el Mundial 2014?', '["6","5","7","4"]'::jsonb, 0, 'medium', 2014, 'goleadores'),
('y-30', '¿Qué selección ganó el Mundial 1954?', '["Alemania Occidental","Hungría","Austria","Uruguay"]'::jsonb, 0, 'hard', 1954, 'campeones'),
('y-31', '¿En qué Mundial debutó Messi con la albiceleste?', '["2006","2010","2014","2002"]'::jsonb, 0, 'easy', 2006, 'leyendas')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;