insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('wc26-012', '¿Qué estadio de Plot Mundial en LA alberga partidos del Grupo D?', '["Estadio Los Ángeles","Rose Bowl","SoFi Stadium","Stanford Stadium"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-013', '¿Qué sede de 2026 está en Seattle?', '["Estadio Seattle","Estadio Portland","Estadio Denver","Estadio Chicago"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-014', '¿Qué sede de 2026 está en Miami?', '["Estadio Miami","Estadio Orlando","Estadio Tampa","Estadio Jacksonville"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-015', '¿Qué sede de 2026 está en Atlanta?', '["Estadio Atlanta","Estadio Nashville","Estadio Charlotte","Estadio New Orleans"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-016', '¿Qué sede de 2026 está en Dallas?', '["Estadio Dallas","Estadio Houston","Estadio San Antonio","Estadio Austin"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-017', '¿Qué sede de 2026 está en Houston?', '["Estadio Houston","Estadio Dallas","Estadio Kansas City","Estadio Phoenix"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-018', '¿Qué sede de 2026 está en Filadelfia?', '["Estadio Filadelfia","Estadio Baltimore","Estadio Washington","Estadio Pittsburgh"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-019', '¿Qué sede de 2026 está en Kansas City?', '["Estadio Kansas City","Estadio Chicago","Estadio Denver","Estadio Minneapolis"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-020', '¿Qué sede de 2026 está en Boston?', '["Estadio Boston","Estadio Nueva York","Estadio Montreal","Estadio Detroit"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-021', '¿Qué sede de 2026 está en la Bahía de San Francisco?', '["Estadio Bahía de San Francisco","Estadio Sacramento","Estadio San Diego","Estadio Las Vegas"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-022', '¿Cuántas sedes en Estados Unidos tendrá el Mundial 2026?', '["11","8","14","9"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-sedes'),
('wc26-023', '¿Cuántas sedes en México tendrá el Mundial 2026?', '["3","2","4","5"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-024', '¿Cuántas sedes en Canadá tendrá el Mundial 2026?', '["2","3","1","4"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-025', '¿Qué estadio mexicano abre el torneo con México vs Sudáfrica?', '["Estadio Ciudad de México","Estadio Guadalajara","Estadio Monterrey","Estadio Azteca histórico solo"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-026', '¿Qué otra ciudad mexicana es sede además de Ciudad de México?', '["Guadalajara y Monterrey","Tijuana y Puebla","Cancún y León","Querétaro y Mérida"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-027', '¿Qué estadio canadiense está en Vancouver?', '["Estadio BC Place Vancouver","Estadio BMO Field","Estadio Olympic","Estadio Rogers Centre"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-028', '¿Qué estadio canadiense está en Toronto?', '["Estadio Toronto","Estadio Montreal","Estadio Calgary","Estadio Ottawa"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-029', '¿Canadá comparte sedes en 2026 con…?', '["Toronto y Vancouver","Montreal y Ottawa","Calgary y Edmonton","Quebec y Winnipeg"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-030', '¿Qué selección NO está en el Grupo A de 2026?', '["Brasil","México","Sudáfrica","Rep. de Corea"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-031', '¿Rep. Checa comparte grupo en 2026 con México y…?', '["Sudáfrica y Corea del Sur","Canadá y Suiza","Estados Unidos y Paraguay","España y Uruguay"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-032', '¿Sudáfrica vuelve al Mundial en 2026 en el grupo de…?', '["México","Brasil","Francia","Alemania"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-033', '¿Canadá comparte Grupo B con Catar, Suiza y…?', '["Bosnia y Herzegovina","Turquía","Ghana","Japón"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-034', '¿Catar clasificó al Mundial 2026 en el grupo…?', '["B","A","H","K"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-grupos'),
('wc26-035', '¿Qué europeo está en el Grupo B junto a Canadá?', '["Suiza","Suecia","Polonia","Serbia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-036', '¿Haití comparte grupo en 2026 con Brasil, Marruecos y…?', '["Escocia","Chile","Perú","Costa Rica"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-037', '¿Escocia juega el Mundial 2026 en el grupo de…?', '["Brasil","Inglaterra","Alemania","España"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-038', '¿Marruecos repite grupo con Brasil en 2026 tras ser semifinalista en…?', '["2022","2018","2014","2010"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-039', '¿Estados Unidos comparte Grupo D con Paraguay, Australia y…?', '["Turquía","México","Canadá","Colombia"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-040', '¿Paraguay está en el Grupo D junto al anfitrión…?', '["Estados Unidos","México","Canadá","Brasil"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-041', '¿Australia juega en 2026 el grupo del anfitrión…?', '["Estados Unidos","Inglaterra","Francia","Alemania"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-042', '¿Curazao debuta en Mundiales en el Grupo E con Alemania y…?', '["Costa de Marfil y Ecuador","Francia y Senegal","España y Uruguay","Portugal y Colombia"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-grupos'),
('wc26-043', '¿Ecuador comparte grupo en 2026 con Alemania y…?', '["Curazao y Costa de Marfil","Japón y Países Bajos","México y Sudáfrica","Ghana e Inglaterra"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-044', '¿Alemania encabeza el Grupo…?', '["E","D","G","I"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-045', '¿Países Bajos comparte Grupo F con Japón, Suecia y…?', '["Túnez","Senegal","Marruecos","Ghana"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-046', '¿Japón está en el Grupo F con Países Bajos y…?', '["Suecia y Túnez","Corea del Sur y México","Irán y Arabia Saudí","Qatar y Australia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-047', '¿Suecia clasificó al Mundial 2026 en el grupo…?', '["F","B","L","H"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-grupos'),
('wc26-048', '¿Bélgica encabeza el Grupo G con Egipto, Irán y…?', '["Nueva Zelanda","Canadá","Ghana","Arabia Saudí"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-049', '¿Irán comparte grupo en 2026 con Bélgica y…?', '["Egipto y Nueva Zelanda","Irak y Noruega","Qatar y Jordania","Turquía y Australia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-050', '¿Nueva Zelanda vuelve a un Mundial en el grupo de…?', '["Bélgica","Argentina","Brasil","Francia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-051', '¿Uruguay comparte Grupo H con España, Arabia Saudita y…?', '["Cabo Verde","Chile","Perú","Paraguay"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;