insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('y-72', '¿Cuántos goles marcó Miroslav Klose en total en Mundiales?', '["16","15","14","17"]'::jsonb, 0, 'medium', null, 'goleadores'),
('y-73', '¿En qué Mundial se jugó el partido "La Mano de Dios" y el "Gol del Siglo"?', '["1986","1982","1990","1978"]'::jsonb, 0, 'easy', 1986, 'momentos'),
('y-74', '¿Quién fue subcampeón en 2010?', '["Holanda","Alemania","Uruguay","España"]'::jsonb, 0, 'medium', 2010, 'campeones'),
('y-75', '¿Qué país organizó el Mundial 2006?', '["Alemania","Francia","Italia","España"]'::jsonb, 0, 'easy', 2006, 'sedes'),
('y-76', '¿Quién marcó el primer gol de Francia en la final 2018?', '["Mandžukić (en contra)","Griezmann","Mbappé","Pogba"]'::jsonb, 0, 'hard', 2018, 'finales'),
('y-77', '¿Cuántos Mundiales ganó Italia?', '["4","3","5","2"]'::jsonb, 0, 'medium', null, 'campeones'),
('y-78', '¿En qué Mundial EEUU llegó a cuartos de final?', '["2002","1994","2010","2014"]'::jsonb, 0, 'medium', 2002, 'records'),
('y-79', '¿Quién fue el entrenador de Argentina en 2022?', '["Scaloni","Sampaoli","Sabella","Bielsa"]'::jsonb, 0, 'easy', 2022, 'selecciones'),
('y-80', '¿Qué selección ganó el primer Mundial en 1930?', '["Uruguay","Argentina","Estados Unidos","Yugoslavia"]'::jsonb, 0, 'easy', 1930, 'campeones'),
('z-001', '¿Qué países organizarán el Mundial 2026?', '["Estados Unidos, México y Canadá","Brasil, Argentina y Chile","España, Portugal e Italia","Qatar, Emiratos y Arabia Saudita"]'::jsonb, 0, 'easy', 2026, 'mundial-2026'),
('z-002', '¿Cuántos equipos participarán en el Mundial 2026?', '["48","32","40","36"]'::jsonb, 0, 'easy', 2026, 'mundial-2026'),
('z-003', '¿Cuántos partidos oficiales habrá en el Mundial 2026?', '["104","96","112","88"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-004', '¿Cuántos grupos tendrá la fase de grupos del Mundial 2026?', '["12","8","16","10"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-005', '¿Dónde se jugará la final del Mundial 2026?', '["MetLife Stadium (NY/NJ)","Estadio Azteca","Rose Bowl","Hard Rock Stadium"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-006', '¿Qué selección abre el Mundial 2026 en el Estadio Ciudad de México?', '["México","Estados Unidos","Canadá","Brasil"]'::jsonb, 0, 'easy', 2026, 'mundial-2026'),
('z-007', '¿Contra qué rival debuta México en el Mundial 2026?', '["Sudáfrica","Corea del Sur","República Checa","Marruecos"]'::jsonb, 0, 'easy', 2026, 'mundial-2026'),
('z-008', '¿En qué grupo está Argentina en el Mundial 2026?', '["Grupo J","Grupo A","Grupo C","Grupo H"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-009', '¿Contra quién debuta Argentina en el Mundial 2026?', '["Argelia","Austria","Jordania","Marruecos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-010', '¿Qué otro equipo europeo comparte grupo con Argentina en 2026?', '["Austria","Alemania","Croacia","Suiza"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-011', '¿Brasil comparte grupo en 2026 con Marruecos y…?', '["Haití y Escocia","Japón y Senegal","Uruguay y Corea del Sur","España y Costa Rica"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-012', '¿Estados Unidos comparte grupo con Paraguay y…?', '["Australia y Turquía","México y Canadá","Ghana y Ecuador","Catar y Suiza"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-013', '¿España comparte grupo en 2026 con Arabia Saudita y…?', '["Cabo Verde y Uruguay","Chile y Perú","Nigeria y Camerún","Polonia y Dinamarca"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-014', '¿Francia comparte grupo en 2026 con Senegal y…?', '["Irak y Noruega","Marruecos y Croacia","Túnez y Ghana","Bélgica y Suiza"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-015', '¿Inglaterra comparte grupo en 2026 con Ghana y…?', '["Panamá y Croacia","Gales y Serbia","Dinamarca y Eslovenia","Irán y EE.UU."]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-016', '¿Alemania comparte grupo en 2026 con Ecuador y…?', '["Costa de Marfil y Curazao","Polonia y Suecia","Serbia y Suiza","Japón y Australia"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-017', '¿Portugal comparte grupo en 2026 con Colombia y…?', '["República Democrática del Congo y Uzbekistán","Brasil y Serbia","Uruguay y Ghana","Croacia y Marruecos"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-018', '¿Cuántas sedes tendrá el Mundial 2026?', '["16","12","20","14"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-019', '¿Qué ciudad canadiense será sede en 2026?', '["Toronto y Vancouver","Montreal solamente","Ottawa y Calgary","Quebec y Winnipeg"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-020', '¿El Mundial 2026 será el primero con cuántos equipos?', '["48","40","36","32"]'::jsonb, 0, 'easy', 2026, 'mundial-2026'),
('z-021', '¿Quién fue el máximo goleador del Mundial 1978?', '["Mario Kempes","Paolo Rossi","Teófilo Cubillas","Rob Rensenbrink"]'::jsonb, 0, 'hard', 1978, 'goleadores'),
('z-022', '¿Quién fue el máximo goleador del Mundial 1986 con 6 goles?', '["Gary Lineker","Diego Maradona","Emilio Butragueño","Careca"]'::jsonb, 0, 'medium', 1986, 'goleadores'),
('z-023', '¿Quién fue el máximo goleador del Mundial 1990?', '["Salvatore Schillaci","Roger Milla","Lothar Matthäus","Tomáš Skuhravý"]'::jsonb, 0, 'medium', 1990, 'goleadores'),
('z-024', '¿Cuántos goles marcó Romário en el Mundial 1994?', '["5","6","4","7"]'::jsonb, 0, 'hard', 1994, 'goleadores'),
('z-025', '¿Oleg Salenko marcó cuántos goles en un partido en 1994?', '["5","4","6","3"]'::jsonb, 0, 'hard', 1994, 'records'),
('z-026', '¿Qué selección anfitriona perdió 7-1 en semifinales en 2014?', '["Brasil","Sudáfrica","Alemania","Rusia"]'::jsonb, 0, 'easy', 2014, 'momentos'),
('z-027', '¿Quién marcó el gol del 1-0 en la final de 2010 para España?', '["Andrés Iniesta","David Villa","Carlos Puyol","Fernando Torres"]'::jsonb, 0, 'easy', 2010, 'finales'),
('z-028', '¿Quién marcó el gol de la victoria en la final de 2014?', '["Mario Götze","André Schürrle","Miroslav Klose","Thomas Müller"]'::jsonb, 0, 'medium', 2014, 'finales'),
('z-029', '¿Quién marcó el tercer gol de Francia en la final 2022?', '["Kylian Mbappé","Olivier Giroud","Antoine Griezmann","Kingsley Coman"]'::jsonb, 0, 'medium', 2022, 'finales'),
('z-030', '¿Qué arquero atajó dos penales en la final 2022?', '["Emiliano Martínez","Hugo Lloris","Alisson","Courtois"]'::jsonb, 0, 'easy', 2022, 'leyendas'),
('z-031', '¿En qué Mundial Pelé marcó un hat-trick en semifinales?', '["1958","1962","1970","1966"]'::jsonb, 0, 'hard', 1958, 'leyendas')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;