insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('wc26-092', '¿Túnez comparte grupo con europeos Países Bajos y…?', '["Suecia","Alemania","Francia","Italia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-curiosidades'),
('wc26-093', '¿El primer partido del fixture Plot Mundial 2026 es…?', '["México vs Sudáfrica","Estados Unidos vs Paraguay","Canadá vs Bosnia","Brasil vs Marruecos"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-calendario'),
('wc26-094', '¿Brasil debuta en 2026 contra…?', '["Marruecos","Haití","Escocia","Uruguay"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-095', '¿Francia debuta en 2026 contra…?', '["Senegal","Irak","Noruega","Marruecos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-096', '¿Alemania debuta en 2026 contra…?', '["Curazao","Ecuador","Costa de Marfil","Estados Unidos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-097', '¿Inglaterra debuta en 2026 contra…?', '["Croacia","Ghana","Panamá","Escocia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-098', '¿Portugal debuta en 2026 contra…?', '["RD Congo","Colombia","Uzbekistán","Brasil"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-099', '¿España debuta en 2026 contra…?', '["Cabo Verde","Uruguay","Arabia Saudita","Chile"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-100', '¿Estados Unidos debuta en 2026 contra…?', '["Paraguay","México","Canadá","Colombia"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-calendario'),
('wc26-101', '¿Los tres anfitriones del 2026 clasifican automáticamente como…?', '["Estados Unidos, México y Canadá","Solo México","México y EE.UU.","Los 6 de CONCACAF"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-formato'),
('wc26-102', '¿México juega en casa en el Grupo…?', '["A","B","D","F"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-103', '¿Canadá juega en casa en el Grupo…?', '["B","A","D","H"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-104', '¿Estados Unidos juega como local en el Grupo…?', '["D","A","B","L"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-105', '¿El Estadio Nueva York Nueva Jersey alberga partidos de 2026 en…?', '["Estados Unidos","Canadá","México","Ningún partido"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-106', '¿El Estadio Guadalajara es sede en…?', '["México","Estados Unidos","Canadá","Guatemala"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-107', '¿El Estadio Monterrey es sede en…?', '["México","Estados Unidos","Canadá","Colombia"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-108', '¿Cuántos grupos tiene letra de la A a la…?', '["L","K","M","J"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-formato'),
('wc26-109', '¿Cuántas confederaciones están representadas en el Mundial 2026?', '["6","5","7","4"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-formato'),
('wc26-110', '¿El Mundial 2026 duplica respecto a 2022 la cantidad de…?', '["Equipos (32 → 48)","Partidos por equipo","Sedes","Grupos de 3"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-formato'),
('wc26-111', '¿Qué selección europea está en el grupo de Brasil en 2026?', '["Escocia","Croacia","Suiza","Serbia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-112', '¿Qué selección africana está en el grupo de España en 2026?', '["Cabo Verde","Senegal","Ghana","Marruecos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-113', '¿Qué selección asiática está en el grupo de Alemania en 2026?', '["Ninguna (grupo sin asiáticos)","Japón","Irán","Qatar"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-situaciones'),
('wc26-114', '¿Qué par de anfitriones NO comparten grupo en 2026?', '["México y Canadá","México y EE.UU.","Canadá y EE.UU.","Todos comparten CONCACAF"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-115', '¿Qué campeón del mundo está en el Grupo J?', '["Argentina","Francia","Alemania","España"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-situaciones'),
('wc26-116', '¿Qué ex campeón está en el Grupo H?', '["España","Uruguay","Inglaterra","Francia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-117', '¿Qué ex campeón está en el Grupo E?', '["Alemania","Brasil","Italia","Argentina"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-118', '¿Italia clasificó al Mundial 2026?', '["No (según el fixture Plot)","Sí, Grupo B","Sí, Grupo F","Sí, repechaje"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-119', '¿Qué selección sudamericana está en el Grupo H con España?', '["Uruguay","Brasil","Colombia","Chile"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-situaciones'),
('wc26-120', '¿Qué selección sudamericana está en el Grupo K con Portugal?', '["Colombia","Uruguay","Paraguay","Chile"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-121', '¿Argentina juega en Kansas City en su primer partido de 2026 contra…?', '["Argelia","Austria","Jordania","Marruecos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-argentina'),
('wc26-122', '¿Argentina vs Austria en 2026 se juega en…?', '["Dallas","Kansas City","Miami","Atlanta"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-argentina'),
('wc26-123', '¿Jordania vs Argentina en 2026 se juega en…?', '["Dallas","Kansas City","Boston","Seattle"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-argentina'),
('wc26-124', '¿Argelia comparte grupo con campeona defensora y…?', '["Austria y Jordania","Brasil y Marruecos","Francia y Senegal","España y Uruguay"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-argentina'),
('wc26-125', '¿Los 16avos de final del 2026 comienzan tras la fase de…?', '["Grupos","Repechaje","Naciones League","Copa Oro"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-formato'),
('wc26-126', '¿Cuántos equipos quedan eliminados en fase de grupos en 2026?', '["16","24","8","32"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-formato'),
('wc26-127', '¿El cuadro eliminatorio de 2026 arranca con…?', '["32 equipos","48 equipos","16 equipos","24 equipos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-formato'),
('wc26-128', '¿La ronda de 8vos en el fixture Plot se llama…?', '["Octavos de final","Cuartos","16avos","Semifinal"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-formato'),
('wc26-129', '¿Qué sede alberga partidos de Argentina en fase de grupos?', '["Kansas City y Dallas","Solo Miami","Los Ángeles y Seattle","Nueva York y Boston"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-sedes'),
('wc26-130', '¿Qué sede mexicana recibe partidos del Grupo A además de Ciudad de México?', '["Guadalajara","Monterrey solamente","Tijuana","Cancún"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-131', '¿Brasil puede jugar partidos de grupos en…?', '["Nueva York, Boston o Filadelfia","Solo México","Solo Canadá","Solo Los Ángeles"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-sedes')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;