insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('champ-2010', '¿Qué selección ganó el Mundial 2010?', '["España","Países Bajos","Alemania","Uruguay"]'::jsonb, 0, 'easy', 2010, 'campeones'),
('champ-2014', '¿Qué selección ganó el Mundial 2014?', '["Alemania","Argentina","Brasil","Países Bajos"]'::jsonb, 0, 'easy', 2014, 'campeones'),
('champ-2018', '¿Qué selección ganó el Mundial 2018?', '["Francia","Croacia","Bélgica","Inglaterra"]'::jsonb, 0, 'easy', 2018, 'campeones'),
('champ-2022', '¿Qué selección ganó el Mundial 2022?', '["Argentina","Francia","Croacia","Marruecos"]'::jsonb, 0, 'easy', 2022, 'campeones'),
('sub-2014', '¿Qué selección fue subcampeona en el Mundial 2014?', '["Argentina","Brasil","Países Bajos","Alemania"]'::jsonb, 0, 'medium', 2014, 'finales'),
('sub-2018', '¿Qué selección fue subcampeona en el Mundial 2018?', '["Croacia","Bélgica","Inglaterra","Francia"]'::jsonb, 0, 'medium', 2018, 'finales'),
('sub-2022', '¿Qué selección fue subcampeona en el Mundial 2022?', '["Francia","Croacia","Marruecos","Argentina"]'::jsonb, 0, 'medium', 2022, 'finales'),
('sub-2010', '¿Qué selección fue subcampeona en el Mundial 2010?', '["Países Bajos","Alemania","Uruguay","España"]'::jsonb, 0, 'medium', 2010, 'finales'),
('sub-2006', '¿Qué selección fue subcampeona en el Mundial 2006?', '["Francia","Alemania","Portugal","Italia"]'::jsonb, 0, 'medium', 2006, 'finales'),
('sub-2002', '¿Qué selección fue subcampeona en el Mundial 2002?', '["Alemania","Brasil","Turquía","Corea del Sur"]'::jsonb, 0, 'medium', 2002, 'finales'),
('sub-1998', '¿Qué selección fue subcampeona en el Mundial 1998?', '["Brasil","Francia","Croacia","Países Bajos"]'::jsonb, 0, 'medium', 1998, 'finales'),
('sub-1994', '¿Qué selección fue subcampeona en el Mundial 1994?', '["Italia","Brasil","Suecia","Bulgaria"]'::jsonb, 0, 'medium', 1994, 'finales'),
('sub-1986', '¿Qué selección fue subcampeona en el Mundial 1986?', '["Alemania Occidental","Argentina","Francia","Bélgica"]'::jsonb, 0, 'medium', 1986, 'finales'),
('sub-1982', '¿Qué selección fue subcampeona en el Mundial 1982?', '["Alemania","Italia","Polonia","Francia"]'::jsonb, 0, 'medium', 1982, 'finales'),
('scorer-2018', '¿Quién fue el máximo goleador del Mundial 2018?', '["Harry Kane","Antoine Griezmann","Romelu Lukaku","Cristiano Ronaldo"]'::jsonb, 0, 'hard', 2018, 'goleadores'),
('scorer-2022', '¿Quién fue el máximo goleador del Mundial 2022?', '["Kylian Mbappé","Lionel Messi","Olivier Giroud","Julián Álvarez"]'::jsonb, 0, 'hard', 2022, 'goleadores'),
('scorer-2014', '¿Quién fue el máximo goleador del Mundial 2014?', '["James Rodríguez","Thomas Müller","Neymar","Lionel Messi"]'::jsonb, 0, 'hard', 2014, 'goleadores'),
('scorer-2010', '¿Quién fue el máximo goleador del Mundial 2010?', '["Diego Forlán","David Villa","Wesley Sneijder","Thomas Müller"]'::jsonb, 0, 'hard', 2010, 'goleadores'),
('scorer-2006', '¿Quién fue el máximo goleador del Mundial 2006?', '["Miroslav Klose","Ronaldo","Hernán Crespo","Thierry Henry"]'::jsonb, 0, 'hard', 2006, 'goleadores'),
('scorer-2002', '¿Quién fue el máximo goleador del Mundial 2002?', '["Ronaldo","Rivaldo","Miroslav Klose","David Beckham"]'::jsonb, 0, 'hard', 2002, 'goleadores'),
('scorer-1998', '¿Quién fue el máximo goleador del Mundial 1998?', '["Davor Šuker","Ronaldo","Dennis Bergkamp","Gabriel Batistuta"]'::jsonb, 0, 'hard', 1998, 'goleadores'),
('scorer-1990', '¿Quién fue el máximo goleador del Mundial 1990?', '["Salvatore Schillaci","Lothar Matthäus","Roger Milla","Gary Lineker"]'::jsonb, 0, 'hard', 1990, 'goleadores'),
('scorer-1986', '¿Quién fue el máximo goleador del Mundial 1986?', '["Gary Lineker","Diego Maradona","Emilio Butragueño","Careca"]'::jsonb, 0, 'hard', 1986, 'goleadores'),
('scorer-1982', '¿Quién fue el máximo goleador del Mundial 1982?', '["Paolo Rossi","Karl-Heinz Rummenigge","Zico","Michel Platini"]'::jsonb, 0, 'hard', 1982, 'goleadores'),
('scorer-1970', '¿Quién fue el máximo goleador del Mundial 1970?', '["Gerd Müller","Pelé","Jairzinho","Tostão"]'::jsonb, 0, 'hard', 1970, 'goleadores'),
('scorer-1966', '¿Quién fue el máximo goleador del Mundial 1966?', '["Eusébio","Geoff Hurst","Franz Beckenbauer","Pelé"]'::jsonb, 0, 'hard', 1966, 'goleadores'),
('rec-1', '¿Qué país ha ganado más Copas del Mundo?', '["Brasil","Alemania","Italia","Argentina"]'::jsonb, 0, 'easy', null, 'records'),
('rec-2', '¿Cuántas Copas del Mundo ganó Brasil hasta 2022?', '["5","4","6","3"]'::jsonb, 0, 'medium', null, 'records'),
('rec-3', '¿Qué selección europea tiene más títulos mundiales?', '["Alemania","Italia","Francia","España"]'::jsonb, 0, 'medium', null, 'records'),
('rec-4', '¿En qué año se jugó el primer Mundial?', '["1930","1928","1934","1926"]'::jsonb, 0, 'easy', 1930, 'records'),
('rec-5', '¿Qué país organizó el primer Mundial?', '["Uruguay","Argentina","Italia","Brasil"]'::jsonb, 0, 'easy', 1930, 'records'),
('rec-6', '¿Qué selección ganó el Mundial 1930?', '["Uruguay","Argentina","Estados Unidos","Yugoslavia"]'::jsonb, 0, 'medium', 1930, 'records'),
('rec-7', '¿Pelé ganó cuántos Mundiales con Brasil?', '["3","2","4","1"]'::jsonb, 0, 'medium', null, 'leyendas'),
('rec-8', '¿Diego Maradona levantó el Mundial en…?', '["1986","1982","1990","1978"]'::jsonb, 0, 'easy', 1986, 'leyendas'),
('rec-9', '¿Lionel Messi ganó su primer Mundial en…?', '["2022","2014","2018","2010"]'::jsonb, 0, 'easy', 2022, 'leyendas'),
('rec-10', '¿Qué país fue campeón en casa en 1966?', '["Inglaterra","Alemania","Portugal","Argentina"]'::jsonb, 0, 'medium', 1966, 'records'),
('rec-11', '¿Brasil ganó su quinto título en…?', '["2002","1994","2006","2010"]'::jsonb, 0, 'medium', 2002, 'records'),
('rec-12', '¿España ganó su único Mundial en…?', '["2010","2006","2014","2018"]'::jsonb, 0, 'easy', 2010, 'records'),
('rec-13', '¿Francia ganó su segundo Mundial en…?', '["2018","2006","1998","2022"]'::jsonb, 0, 'medium', 2018, 'records'),
('rec-14', '¿Italia tiene cuántos títulos mundiales?', '["4","3","5","2"]'::jsonb, 0, 'hard', null, 'records')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;