insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('gol-012', '¿Quién fue el máximo goleador del Mundial 1982?', '["Paolo Rossi","Karl-Heinz Rummenigge","Zico","Michel Platini"]'::jsonb, 0, 'medium', 1982, 'goleadores'),
('gol-013', '¿Cuántos goles marcó Paolo Rossi en España 1982?', '["6","5","7","8"]'::jsonb, 0, 'medium', 1982, 'goleadores'),
('gol-014', '¿Quién fue el máximo goleador del Mundial 1994?', '["Hristo Stoichkov y Oleg Salenko (6)","Romário","Roberto Baggio","Dennis Bergkamp"]'::jsonb, 0, 'hard', 1994, 'goleadores'),
('gol-015', '¿Quién fue el máximo goleador del Mundial 1998?', '["Davor Šuker","Ronaldo","Dennis Bergkamp","Gabriel Batistuta"]'::jsonb, 0, 'medium', 1998, 'goleadores'),
('gol-016', '¿Cuántos goles marcó Šuker en Francia 1998?', '["6","5","7","8"]'::jsonb, 0, 'hard', 1998, 'goleadores'),
('gol-017', '¿Cuántos goles marcó Miroslav Klose como goleador del Mundial 2006?', '["5","6","4","7"]'::jsonb, 0, 'medium', 2006, 'goleadores'),
('gol-018', '¿Cuántos goles marcó Thomas Müller en Sudáfrica 2010?', '["5","4","6","7"]'::jsonb, 0, 'medium', 2010, 'goleadores'),
('gol-019', '¿Quién fue el máximo goleador del Mundial 2010?', '["Diego Forlán, Wesley Sneijder, David Villa y Thomas Müller (5)","Lionel Messi","David Villa solo","Diego Forlán solo"]'::jsonb, 0, 'hard', 2010, 'goleadores'),
('gol-020', '¿Cuántos goles marcó Mbappé en todo Qatar 2022?', '["8","6","7","9"]'::jsonb, 0, 'medium', 2022, 'goleadores'),
('gol-021', '¿Cuántos goles marcó Lionel Messi en Qatar 2022?', '["7","5","8","6"]'::jsonb, 0, 'medium', 2022, 'goleadores'),
('gol-022', '¿Cuántos goles marcó Julián Álvarez en Qatar 2022?', '["4","3","5","6"]'::jsonb, 0, 'medium', 2022, 'goleadores'),
('gol-023', '¿Cuántos goles marcó Olivier Giroud en Qatar 2022?', '["4","3","5","2"]'::jsonb, 0, 'medium', 2022, 'goleadores'),
('gol-024', '¿Quién tiene el récord de más goles en un solo Mundial (13)?', '["Just Fontaine","Miroslav Klose","Ronaldo","Gerd Müller"]'::jsonb, 0, 'medium', 1958, 'goles-records'),
('gol-025', '¿En qué Mundial Fontaine marcó sus 13 goles?', '["1958","1962","1954","1966"]'::jsonb, 0, 'medium', 1958, 'goles-records'),
('gol-026', '¿Quién superó a Ronaldo (15) como goleador histórico en 2014?', '["Miroslav Klose","Lionel Messi","Thomas Müller","Pelé"]'::jsonb, 0, 'easy', 2014, 'goleadores'),
('gol-027', '¿En qué partido Klose igualó el récord de Ronaldo y luego lo superó?', '["Semifinal 2014 vs Brasil","Final 2014","Cuartos 2014","Grupos 2010"]'::jsonb, 0, 'hard', 2014, 'goleadores'),
('gol-028', '¿Cuántos goles marcó Pelé en finales de Mundial?', '["3","2","4","5"]'::jsonb, 0, 'hard', null, 'goles-records'),
('gol-029', '¿Cuántos Mundiales distintos marcó gol Miroslav Klose?', '["4","3","5","2"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-030', '¿Cuántos Mundiales distintos marcó gol Lionel Messi?', '["5","4","3","6"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-031', '¿Cuántos goles marcó Cristiano Ronaldo en Mundiales (hasta 2022)?', '["8","7","9","10"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-032', '¿Cuántos goles marcó Kylian Mbappé en Mundiales (hasta 2022)?', '["12","10","8","14"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-033', '¿Quién es el máximo goleador de Brasil en Mundiales?', '["Ronaldo con 15","Pelé","Romário","Neymar"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-034', '¿Cuántos goles mundialistas tiene Neymar (hasta 2022)?', '["8","10","6","7"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-035', '¿Cuántos goles marcó Diego Maradona en Mundiales?', '["8","10","6","12"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-036', '¿Cuántos goles marcó Gabriel Batistuta en Mundiales?', '["10","8","12","6"]'::jsonb, 0, 'hard', null, 'goleadores'),
('gol-037', '¿Cuántos goles marcó Jürgen Klinsmann en Mundiales?', '["11","9","13","8"]'::jsonb, 0, 'hard', null, 'goleadores'),
('gol-038', '¿Cuántos goles marcó Teófilo Cubillas en Mundiales?', '["10","8","12","6"]'::jsonb, 0, 'hard', null, 'goleadores'),
('gol-039', '¿Quién marcó 5 goles en un partido del Mundial 1994?', '["Oleg Salenko","Romário","Hristo Stoichkov","Dennis Bergkamp"]'::jsonb, 0, 'medium', 1994, 'goles-records'),
('gol-040', '¿Contra qué selección Salenko marcó 5 goles en 1994?', '["Camerún","México","Suecia","Colombia"]'::jsonb, 0, 'hard', 1994, 'goles-records'),
('gol-041', '¿Cuál es el resultado más abultado en un Mundial?', '["Hungria 10-1 El Salvador (1982)","Alemania 8-0 Arabia Saudita","Yugoslavia 9-0 Zaire","Uruguay 7-0 Escocia"]'::jsonb, 0, 'hard', 1982, 'goles-records'),
('gol-042', '¿Geoff Hurst marcó un hat-trick en la final de…?', '["1966","1970","1962","1974"]'::jsonb, 0, 'easy', 1966, 'goles-finales'),
('gol-043', '¿Antes de Mbappé en 2022, ¿quién había hecho hat-trick en una final?', '["Geoff Hurst (1966)","Pelé","Ronaldo","Zidane"]'::jsonb, 0, 'medium', 2022, 'goles-finales'),
('gol-044', '¿Mbappé anotó 3 goles en la final 2022 pero…?', '["Francia igual perdió en penales","Francia ganó","Fue expulsado","No hubo prórroga"]'::jsonb, 0, 'easy', 2022, 'goles-finales'),
('gol-045', '¿Cuántos goles marcó Rusia (URSS) en el partido vs Camerún en 1994?', '["6","5","7","4"]'::jsonb, 0, 'hard', 1994, 'goles-records'),
('gol-046', '¿Alemania marcó 7 goles contra Brasil en semifinales de…?', '["2014","2010","2018","2002"]'::jsonb, 0, 'easy', 2014, 'goles-records'),
('gol-047', '¿España marcó 7-0 a Costa Rica en el Mundial…?', '["2022","2010","2014","2018"]'::jsonb, 0, 'easy', 2022, 'goles-records'),
('gol-048', '¿Quién marcó dos goles en la final de 1978 para Argentina?', '["Mario Kempes","Leopoldo Luque","Daniel Passarella","Daniel Bertoni"]'::jsonb, 0, 'hard', 1978, 'goles-finales'),
('gol-049', '¿Cuál es el gol más rápido en la historia del Mundial?', '["Hakan Şükür (~11 segundos)","Clint Dempsey (~29 seg)","Bryan Robson (~27 seg)","Emile Mpenza (~20 seg)"]'::jsonb, 0, 'hard', 2002, 'goles-minutos'),
('gol-050', '¿Şükür marcó el gol más rápido en 2002 contra…?', '["Corea del Sur","Turquía no — Turquía marcó","Brasil","Senegal"]'::jsonb, 0, 'hard', 2002, 'goles-minutos'),
('gol-051', '¿Clint Dempsey marcó el gol más rápido de USA en 2014 al minuto…?', '["29 segundos","11 segundos","45 segundos","2 minutos"]'::jsonb, 0, 'hard', 2014, 'goles-minutos')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;