insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('y-32', '¿Quién ganó el Mundial 1938?', '["Italia","Hungría","Brasil","Francia"]'::jsonb, 0, 'hard', 1938, 'campeones'),
('y-33', '¿Qué país organizó el Mundial 2010?', '["Sudáfrica","Egipto","Marruecos","Nigeria"]'::jsonb, 0, 'easy', 2010, 'sedes'),
('y-34', '¿Quién fue capitán de Francia en la final 2018?', '["Lloris","Griezmann","Pogba","Varane"]'::jsonb, 0, 'medium', 2018, 'selecciones'),
('y-35', '¿Cuántos Mundiales ganó Brasil?', '["5","4","6","3"]'::jsonb, 0, 'easy', null, 'campeones'),
('y-36', '¿Qué país eliminó a Alemania en semifinales en 2010?', '["España","Argentina","Holanda","Uruguay"]'::jsonb, 0, 'medium', 2010, 'momentos'),
('y-37', '¿Quién marcó el gol de la victoria en la final 1998?', '["Zidane","Henry","Petit","Trezeguet"]'::jsonb, 0, 'medium', 1998, 'finales'),
('y-38', '¿En qué Mundial se jugó el partido "Maracanazo"?', '["1950","1930","1962","1970"]'::jsonb, 0, 'medium', 1950, 'momentos'),
('y-39', '¿Qué selección ganó el Mundial 1962?', '["Brasil","Chile","Checoslovaquia","Yugoslavia"]'::jsonb, 0, 'medium', 1962, 'campeones'),
('y-40', '¿Quién fue el máximo goleador del Mundial 2018?', '["Kane","Lukaku","Griezmann","Mbappé"]'::jsonb, 0, 'medium', 2018, 'goleadores'),
('y-41', '¿Qué país organizó el Mundial 1986?', '["México","Colombia","Estados Unidos","Argentina"]'::jsonb, 0, 'easy', 1986, 'sedes'),
('y-42', '¿Cuántos goles marcó Mbappé en la final 2022?', '["3","2","4","1"]'::jsonb, 0, 'medium', 2022, 'finales'),
('y-43', '¿Quién ganó el Mundial 2006?', '["Italia","Francia","Alemania","Brasil"]'::jsonb, 0, 'easy', 2006, 'campeones'),
('y-44', '¿Qué país fue subcampeón en 1974?', '["Holanda","Brasil","Polonia","Alemania Oriental"]'::jsonb, 0, 'medium', 1974, 'campeones'),
('y-45', '¿En qué Mundial Bélgica terminó tercera?', '["2018","1986","2002","2022"]'::jsonb, 0, 'medium', 2018, 'records'),
('y-46', '¿Quién marcó el gol del 1-0 en la final 2010 para España?', '["Iniesta","Villa","Puyol","Torres"]'::jsonb, 0, 'easy', 2010, 'finales'),
('y-47', '¿Qué selección ganó el Mundial 1970?', '["Brasil","Italia","Alemania","Uruguay"]'::jsonb, 0, 'easy', 1970, 'campeones'),
('y-48', '¿Cuántos equipos habrá en el Mundial 2026?', '["48","40","32","36"]'::jsonb, 0, 'medium', 2026, 'formato'),
('y-49', '¿Quién fue el entrenador de Alemania en 2014?', '["Löw","Klinsmann","Flick","Nagelsmann"]'::jsonb, 0, 'medium', 2014, 'selecciones'),
('y-50', '¿Qué país ganó el Mundial 1998?', '["Francia","Brasil","Croacia","Holanda"]'::jsonb, 0, 'easy', 1998, 'campeones'),
('y-51', '¿En qué Mundial Corea del Sur llegó a semifinales?', '["2002","2010","2006","2018"]'::jsonb, 0, 'medium', 2002, 'records'),
('y-52', '¿Quién marcó el penal decisivo en la final 2006?', '["Grosso","Del Piero","Totti","Cannavaro"]'::jsonb, 0, 'hard', 2006, 'finales'),
('y-53', '¿Qué país organizó el Mundial 1978?', '["Argentina","Brasil","Uruguay","Chile"]'::jsonb, 0, 'easy', 1978, 'sedes'),
('y-54', '¿Cuántos Mundiales ganó Argentina hasta 2022?', '["3","2","4","1"]'::jsonb, 0, 'medium', null, 'campeones'),
('y-55', '¿Quién fue el goleador del Mundial 2006?', '["Klose","Ronaldo","Podolski","Ribéry"]'::jsonb, 0, 'medium', 2006, 'goleadores'),
('y-56', '¿Qué selección ganó el Mundial 1950 en Brasil?', '["Uruguay","Brasil","España","Suecia"]'::jsonb, 0, 'hard', 1950, 'campeones'),
('y-57', '¿En qué Mundial se introdujo el sistema de dos grupos en segunda fase?', '["1982","1978","1986","1990"]'::jsonb, 0, 'hard', 1982, 'formato'),
('y-58', '¿Quién marcó el gol de cabeza famoso en 1970 contra Italia?', '["Pelé","Jairzinho","Tostão","Rivelino"]'::jsonb, 0, 'medium', 1970, 'momentos'),
('y-59', '¿Qué país fue sede del Mundial 1966?', '["Inglaterra","Francia","Alemania","España"]'::jsonb, 0, 'easy', 1966, 'sedes'),
('y-60', '¿Quién ganó el Mundial 2018?', '["Francia","Croacia","Bélgica","Inglaterra"]'::jsonb, 0, 'easy', 2018, 'campeones'),
('y-61', '¿Cuántos goles marcó Pelé en Mundiales?', '["12","10","15","8"]'::jsonb, 0, 'hard', null, 'leyendas'),
('y-62', '¿Qué país eliminó a España en octavos en 2022?', '["Marruecos","Croacia","Brasil","Alemania"]'::jsonb, 0, 'medium', 2022, 'momentos'),
('y-63', '¿En qué Mundial debutó la mascota World Cup Willie?', '["1966","1958","1970","1974"]'::jsonb, 0, 'hard', 1966, 'curiosidades'),
('y-64', '¿Quién fue el máximo goleador del Mundial 1990?', '["Schillaci","Lineker","Matthäus","Voller"]'::jsonb, 0, 'medium', 1990, 'goleadores'),
('y-65', '¿Qué selección ganó el Mundial 2002?', '["Brasil","Alemania","Turquía","Corea del Sur"]'::jsonb, 0, 'easy', 2002, 'campeones'),
('y-66', '¿Cuántas finales mundialistas perdió Holanda?', '["3","2","4","1"]'::jsonb, 0, 'hard', null, 'records'),
('y-67', '¿Quién marcó el gol del 3-2 en la final 2022 en tiempo extra?', '["Messi","Di María","Álvarez","Mac Allister"]'::jsonb, 0, 'easy', 2022, 'finales'),
('y-68', '¿Qué país organizó el Mundial 1950?', '["Brasil","Uruguay","Argentina","Chile"]'::jsonb, 0, 'medium', 1950, 'sedes'),
('y-69', '¿En qué Mundial Italia ganó en casa?', '["1934","1990","1982","2006"]'::jsonb, 0, 'hard', 1934, 'campeones'),
('y-70', '¿Quién fue el arquero de Brasil en 2002?', '["Marcos","Dida","Cássio","Taffarel"]'::jsonb, 0, 'hard', 2002, 'selecciones'),
('y-71', '¿Qué país ganó el Mundial 2014?', '["Alemania","Argentina","Brasil","Holanda"]'::jsonb, 0, 'easy', 2014, 'campeones')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;