insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('wc26-092', '┬┐T├║nez comparte grupo con europeos Pa├¡ses Bajos yÔÇª?', '["Suecia","Alemania","Francia","Italia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-curiosidades'),
('wc26-093', '┬┐El primer partido del fixture Plot Mundial 2026 esÔÇª?', '["M├®xico vs Sud├ífrica","Estados Unidos vs Paraguay","Canad├í vs Bosnia","Brasil vs Marruecos"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-calendario'),
('wc26-094', '┬┐Brasil debuta en 2026 contraÔÇª?', '["Marruecos","Hait├¡","Escocia","Uruguay"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-095', '┬┐Francia debuta en 2026 contraÔÇª?', '["Senegal","Irak","Noruega","Marruecos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-096', '┬┐Alemania debuta en 2026 contraÔÇª?', '["Curazao","Ecuador","Costa de Marfil","Estados Unidos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-097', '┬┐Inglaterra debuta en 2026 contraÔÇª?', '["Croacia","Ghana","Panam├í","Escocia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-098', '┬┐Portugal debuta en 2026 contraÔÇª?', '["RD Congo","Colombia","Uzbekist├ín","Brasil"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-099', '┬┐Espa├▒a debuta en 2026 contraÔÇª?', '["Cabo Verde","Uruguay","Arabia Saudita","Chile"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-calendario'),
('wc26-100', '┬┐Estados Unidos debuta en 2026 contraÔÇª?', '["Paraguay","M├®xico","Canad├í","Colombia"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-calendario'),
('wc26-101', '┬┐Los tres anfitriones del 2026 clasifican autom├íticamente comoÔÇª?', '["Estados Unidos, M├®xico y Canad├í","Solo M├®xico","M├®xico y EE.UU.","Los 6 de CONCACAF"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-formato'),
('wc26-102', '┬┐M├®xico juega en casa en el GrupoÔÇª?', '["A","B","D","F"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-103', '┬┐Canad├í juega en casa en el GrupoÔÇª?', '["B","A","D","H"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-104', '┬┐Estados Unidos juega como local en el GrupoÔÇª?', '["D","A","B","L"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-105', '┬┐El Estadio Nueva York Nueva Jersey alberga partidos de 2026 enÔÇª?', '["Estados Unidos","Canad├í","M├®xico","Ning├║n partido"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-106', '┬┐El Estadio Guadalajara es sede enÔÇª?', '["M├®xico","Estados Unidos","Canad├í","Guatemala"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-107', '┬┐El Estadio Monterrey es sede enÔÇª?', '["M├®xico","Estados Unidos","Canad├í","Colombia"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-108', '┬┐Cu├íntos grupos tiene letra de la A a laÔÇª?', '["L","K","M","J"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-formato'),
('wc26-109', '┬┐Cu├íntas confederaciones est├ín representadas en el Mundial 2026?', '["6","5","7","4"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-formato'),
('wc26-110', '┬┐El Mundial 2026 duplica respecto a 2022 la cantidad deÔÇª?', '["Equipos (32 ÔåÆ 48)","Partidos por equipo","Sedes","Grupos de 3"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-formato'),
('wc26-111', '┬┐Qu├® selecci├│n europea est├í en el grupo de Brasil en 2026?', '["Escocia","Croacia","Suiza","Serbia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-112', '┬┐Qu├® selecci├│n africana est├í en el grupo de Espa├▒a en 2026?', '["Cabo Verde","Senegal","Ghana","Marruecos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-113', '┬┐Qu├® selecci├│n asi├ítica est├í en el grupo de Alemania en 2026?', '["Ninguna (grupo sin asi├íticos)","Jap├│n","Ir├ín","Qatar"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-situaciones'),
('wc26-114', '┬┐Qu├® par de anfitriones NO comparten grupo en 2026?', '["M├®xico y Canad├í","M├®xico y EE.UU.","Canad├í y EE.UU.","Todos comparten CONCACAF"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-115', '┬┐Qu├® campe├│n del mundo est├í en el Grupo J?', '["Argentina","Francia","Alemania","Espa├▒a"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-situaciones'),
('wc26-116', '┬┐Qu├® ex campe├│n est├í en el Grupo H?', '["Espa├▒a","Uruguay","Inglaterra","Francia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-117', '┬┐Qu├® ex campe├│n est├í en el Grupo E?', '["Alemania","Brasil","Italia","Argentina"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-118', '┬┐Italia clasific├│ al Mundial 2026?', '["No (seg├║n el fixture Plot)","S├¡, Grupo B","S├¡, Grupo F","S├¡, repechaje"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-119', '┬┐Qu├® selecci├│n sudamericana est├í en el Grupo H con Espa├▒a?', '["Uruguay","Brasil","Colombia","Chile"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-situaciones'),
('wc26-120', '┬┐Qu├® selecci├│n sudamericana est├í en el Grupo K con Portugal?', '["Colombia","Uruguay","Paraguay","Chile"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-situaciones'),
('wc26-121', '┬┐Argentina juega en Kansas City en su primer partido de 2026 contraÔÇª?', '["Argelia","Austria","Jordania","Marruecos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-argentina'),
('wc26-122', '┬┐Argentina vs Austria en 2026 se juega enÔÇª?', '["Dallas","Kansas City","Miami","Atlanta"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-argentina'),
('wc26-123', '┬┐Jordania vs Argentina en 2026 se juega enÔÇª?', '["Dallas","Kansas City","Boston","Seattle"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-argentina'),
('wc26-124', '┬┐Argelia comparte grupo con campeona defensora yÔÇª?', '["Austria y Jordania","Brasil y Marruecos","Francia y Senegal","Espa├▒a y Uruguay"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-argentina'),
('wc26-125', '┬┐Los 16avos de final del 2026 comienzan tras la fase deÔÇª?', '["Grupos","Repechaje","Naciones League","Copa Oro"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-formato'),
('wc26-126', '┬┐Cu├íntos equipos quedan eliminados en fase de grupos en 2026?', '["16","24","8","32"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-formato'),
('wc26-127', '┬┐El cuadro eliminatorio de 2026 arranca conÔÇª?', '["32 equipos","48 equipos","16 equipos","24 equipos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-formato'),
('wc26-128', '┬┐La ronda de 8vos en el fixture Plot se llamaÔÇª?', '["Octavos de final","Cuartos","16avos","Semifinal"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-formato'),
('wc26-129', '┬┐Qu├® sede alberga partidos de Argentina en fase de grupos?', '["Kansas City y Dallas","Solo Miami","Los ├üngeles y Seattle","Nueva York y Boston"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-sedes'),
('wc26-130', '┬┐Qu├® sede mexicana recibe partidos del Grupo A adem├ís de Ciudad de M├®xico?', '["Guadalajara","Monterrey solamente","Tijuana","Canc├║n"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-131', '┬┐Brasil puede jugar partidos de grupos enÔÇª?', '["Nueva York, Boston o Filadelfia","Solo M├®xico","Solo Canad├í","Solo Los ├üngeles"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-sedes')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;
