insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('y-72', '┬┐Cu├íntos goles marc├│ Miroslav Klose en total en Mundiales?', '["16","15","14","17"]'::jsonb, 0, 'medium', null, 'goleadores'),
('y-73', '┬┐En qu├® Mundial se jug├│ el partido "La Mano de Dios" y el "Gol del Siglo"?', '["1986","1982","1990","1978"]'::jsonb, 0, 'easy', 1986, 'momentos'),
('y-74', '┬┐Qui├®n fue subcampe├│n en 2010?', '["Holanda","Alemania","Uruguay","Espa├▒a"]'::jsonb, 0, 'medium', 2010, 'campeones'),
('y-75', '┬┐Qu├® pa├¡s organiz├│ el Mundial 2006?', '["Alemania","Francia","Italia","Espa├▒a"]'::jsonb, 0, 'easy', 2006, 'sedes'),
('y-76', '┬┐Qui├®n marc├│ el primer gol de Francia en la final 2018?', '["Mand┼¥uki─ç (en contra)","Griezmann","Mbapp├®","Pogba"]'::jsonb, 0, 'hard', 2018, 'finales'),
('y-77', '┬┐Cu├íntos Mundiales gan├│ Italia?', '["4","3","5","2"]'::jsonb, 0, 'medium', null, 'campeones'),
('y-78', '┬┐En qu├® Mundial EEUU lleg├│ a cuartos de final?', '["2002","1994","2010","2014"]'::jsonb, 0, 'medium', 2002, 'records'),
('y-79', '┬┐Qui├®n fue el entrenador de Argentina en 2022?', '["Scaloni","Sampaoli","Sabella","Bielsa"]'::jsonb, 0, 'easy', 2022, 'selecciones'),
('y-80', '┬┐Qu├® selecci├│n gan├│ el primer Mundial en 1930?', '["Uruguay","Argentina","Estados Unidos","Yugoslavia"]'::jsonb, 0, 'easy', 1930, 'campeones'),
('z-001', '┬┐Qu├® pa├¡ses organizar├ín el Mundial 2026?', '["Estados Unidos, M├®xico y Canad├í","Brasil, Argentina y Chile","Espa├▒a, Portugal e Italia","Qatar, Emiratos y Arabia Saudita"]'::jsonb, 0, 'easy', 2026, 'mundial-2026'),
('z-002', '┬┐Cu├íntos equipos participar├ín en el Mundial 2026?', '["48","32","40","36"]'::jsonb, 0, 'easy', 2026, 'mundial-2026'),
('z-003', '┬┐Cu├íntos partidos oficiales habr├í en el Mundial 2026?', '["104","96","112","88"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-004', '┬┐Cu├íntos grupos tendr├í la fase de grupos del Mundial 2026?', '["12","8","16","10"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-005', '┬┐D├│nde se jugar├í la final del Mundial 2026?', '["MetLife Stadium (NY/NJ)","Estadio Azteca","Rose Bowl","Hard Rock Stadium"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-006', '┬┐Qu├® selecci├│n abre el Mundial 2026 en el Estadio Ciudad de M├®xico?', '["M├®xico","Estados Unidos","Canad├í","Brasil"]'::jsonb, 0, 'easy', 2026, 'mundial-2026'),
('z-007', '┬┐Contra qu├® rival debuta M├®xico en el Mundial 2026?', '["Sud├ífrica","Corea del Sur","Rep├║blica Checa","Marruecos"]'::jsonb, 0, 'easy', 2026, 'mundial-2026'),
('z-008', '┬┐En qu├® grupo est├í Argentina en el Mundial 2026?', '["Grupo J","Grupo A","Grupo C","Grupo H"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-009', '┬┐Contra qui├®n debuta Argentina en el Mundial 2026?', '["Argelia","Austria","Jordania","Marruecos"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-010', '┬┐Qu├® otro equipo europeo comparte grupo con Argentina en 2026?', '["Austria","Alemania","Croacia","Suiza"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-011', '┬┐Brasil comparte grupo en 2026 con Marruecos yÔÇª?', '["Hait├¡ y Escocia","Jap├│n y Senegal","Uruguay y Corea del Sur","Espa├▒a y Costa Rica"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-012', '┬┐Estados Unidos comparte grupo con Paraguay yÔÇª?', '["Australia y Turqu├¡a","M├®xico y Canad├í","Ghana y Ecuador","Catar y Suiza"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-013', '┬┐Espa├▒a comparte grupo en 2026 con Arabia Saudita yÔÇª?', '["Cabo Verde y Uruguay","Chile y Per├║","Nigeria y Camer├║n","Polonia y Dinamarca"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-014', '┬┐Francia comparte grupo en 2026 con Senegal yÔÇª?', '["Irak y Noruega","Marruecos y Croacia","T├║nez y Ghana","B├®lgica y Suiza"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-015', '┬┐Inglaterra comparte grupo en 2026 con Ghana yÔÇª?', '["Panam├í y Croacia","Gales y Serbia","Dinamarca y Eslovenia","Ir├ín y EE.UU."]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-016', '┬┐Alemania comparte grupo en 2026 con Ecuador yÔÇª?', '["Costa de Marfil y Curazao","Polonia y Suecia","Serbia y Suiza","Jap├│n y Australia"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-017', '┬┐Portugal comparte grupo en 2026 con Colombia yÔÇª?', '["Rep├║blica Democr├ítica del Congo y Uzbekist├ín","Brasil y Serbia","Uruguay y Ghana","Croacia y Marruecos"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-018', '┬┐Cu├íntas sedes tendr├í el Mundial 2026?', '["16","12","20","14"]'::jsonb, 0, 'medium', 2026, 'mundial-2026'),
('z-019', '┬┐Qu├® ciudad canadiense ser├í sede en 2026?', '["Toronto y Vancouver","Montreal solamente","Ottawa y Calgary","Quebec y Winnipeg"]'::jsonb, 0, 'hard', 2026, 'mundial-2026'),
('z-020', '┬┐El Mundial 2026 ser├í el primero con cu├íntos equipos?', '["48","40","36","32"]'::jsonb, 0, 'easy', 2026, 'mundial-2026'),
('z-021', '┬┐Qui├®n fue el m├íximo goleador del Mundial 1978?', '["Mario Kempes","Paolo Rossi","Te├│filo Cubillas","Rob Rensenbrink"]'::jsonb, 0, 'hard', 1978, 'goleadores'),
('z-022', '┬┐Qui├®n fue el m├íximo goleador del Mundial 1986 con 6 goles?', '["Gary Lineker","Diego Maradona","Emilio Butrague├▒o","Careca"]'::jsonb, 0, 'medium', 1986, 'goleadores'),
('z-023', '┬┐Qui├®n fue el m├íximo goleador del Mundial 1990?', '["Salvatore Schillaci","Roger Milla","Lothar Matth├ñus","Tom├í┼í Skuhrav├¢"]'::jsonb, 0, 'medium', 1990, 'goleadores'),
('z-024', '┬┐Cu├íntos goles marc├│ Rom├írio en el Mundial 1994?', '["5","6","4","7"]'::jsonb, 0, 'hard', 1994, 'goleadores'),
('z-025', '┬┐Oleg Salenko marc├│ cu├íntos goles en un partido en 1994?', '["5","4","6","3"]'::jsonb, 0, 'hard', 1994, 'records'),
('z-026', '┬┐Qu├® selecci├│n anfitriona perdi├│ 7-1 en semifinales en 2014?', '["Brasil","Sud├ífrica","Alemania","Rusia"]'::jsonb, 0, 'easy', 2014, 'momentos'),
('z-027', '┬┐Qui├®n marc├│ el gol del 1-0 en la final de 2010 para Espa├▒a?', '["Andr├®s Iniesta","David Villa","Carlos Puyol","Fernando Torres"]'::jsonb, 0, 'easy', 2010, 'finales'),
('z-028', '┬┐Qui├®n marc├│ el gol de la victoria en la final de 2014?', '["Mario G├Âtze","Andr├® Sch├╝rrle","Miroslav Klose","Thomas M├╝ller"]'::jsonb, 0, 'medium', 2014, 'finales'),
('z-029', '┬┐Qui├®n marc├│ el tercer gol de Francia en la final 2022?', '["Kylian Mbapp├®","Olivier Giroud","Antoine Griezmann","Kingsley Coman"]'::jsonb, 0, 'medium', 2022, 'finales'),
('z-030', '┬┐Qu├® arquero ataj├│ dos penales en la final 2022?', '["Emiliano Mart├¡nez","Hugo Lloris","Alisson","Courtois"]'::jsonb, 0, 'easy', 2022, 'leyendas'),
('z-031', '┬┐En qu├® Mundial Pel├® marc├│ un hat-trick en semifinales?', '["1958","1962","1970","1966"]'::jsonb, 0, 'hard', 1958, 'leyendas')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;
