insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('wc26-012', '┬┐Qu├® estadio de Plot Mundial en LA alberga partidos del Grupo D?', '["Estadio Los ├üngeles","Rose Bowl","SoFi Stadium","Stanford Stadium"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-013', '┬┐Qu├® sede de 2026 est├í en Seattle?', '["Estadio Seattle","Estadio Portland","Estadio Denver","Estadio Chicago"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-014', '┬┐Qu├® sede de 2026 est├í en Miami?', '["Estadio Miami","Estadio Orlando","Estadio Tampa","Estadio Jacksonville"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-015', '┬┐Qu├® sede de 2026 est├í en Atlanta?', '["Estadio Atlanta","Estadio Nashville","Estadio Charlotte","Estadio New Orleans"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-016', '┬┐Qu├® sede de 2026 est├í en Dallas?', '["Estadio Dallas","Estadio Houston","Estadio San Antonio","Estadio Austin"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-017', '┬┐Qu├® sede de 2026 est├í en Houston?', '["Estadio Houston","Estadio Dallas","Estadio Kansas City","Estadio Phoenix"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-018', '┬┐Qu├® sede de 2026 est├í en Filadelfia?', '["Estadio Filadelfia","Estadio Baltimore","Estadio Washington","Estadio Pittsburgh"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-019', '┬┐Qu├® sede de 2026 est├í en Kansas City?', '["Estadio Kansas City","Estadio Chicago","Estadio Denver","Estadio Minneapolis"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-020', '┬┐Qu├® sede de 2026 est├í en Boston?', '["Estadio Boston","Estadio Nueva York","Estadio Montreal","Estadio Detroit"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-021', '┬┐Qu├® sede de 2026 est├í en la Bah├¡a de San Francisco?', '["Estadio Bah├¡a de San Francisco","Estadio Sacramento","Estadio San Diego","Estadio Las Vegas"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-022', '┬┐Cu├íntas sedes en Estados Unidos tendr├í el Mundial 2026?', '["11","8","14","9"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-sedes'),
('wc26-023', '┬┐Cu├íntas sedes en M├®xico tendr├í el Mundial 2026?', '["3","2","4","5"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-024', '┬┐Cu├íntas sedes en Canad├í tendr├í el Mundial 2026?', '["2","3","1","4"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-025', '┬┐Qu├® estadio mexicano abre el torneo con M├®xico vs Sud├ífrica?', '["Estadio Ciudad de M├®xico","Estadio Guadalajara","Estadio Monterrey","Estadio Azteca hist├│rico solo"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-026', '┬┐Qu├® otra ciudad mexicana es sede adem├ís de Ciudad de M├®xico?', '["Guadalajara y Monterrey","Tijuana y Puebla","Canc├║n y Le├│n","Quer├®taro y M├®rida"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-027', '┬┐Qu├® estadio canadiense est├í en Vancouver?', '["Estadio BC Place Vancouver","Estadio BMO Field","Estadio Olympic","Estadio Rogers Centre"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-028', '┬┐Qu├® estadio canadiense est├í en Toronto?', '["Estadio Toronto","Estadio Montreal","Estadio Calgary","Estadio Ottawa"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-sedes'),
('wc26-029', '┬┐Canad├í comparte sedes en 2026 conÔÇª?', '["Toronto y Vancouver","Montreal y Ottawa","Calgary y Edmonton","Quebec y Winnipeg"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-sedes'),
('wc26-030', '┬┐Qu├® selecci├│n NO est├í en el Grupo A de 2026?', '["Brasil","M├®xico","Sud├ífrica","Rep. de Corea"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-031', '┬┐Rep. Checa comparte grupo en 2026 con M├®xico yÔÇª?', '["Sud├ífrica y Corea del Sur","Canad├í y Suiza","Estados Unidos y Paraguay","Espa├▒a y Uruguay"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-032', '┬┐Sud├ífrica vuelve al Mundial en 2026 en el grupo deÔÇª?', '["M├®xico","Brasil","Francia","Alemania"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-033', '┬┐Canad├í comparte Grupo B con Catar, Suiza yÔÇª?', '["Bosnia y Herzegovina","Turqu├¡a","Ghana","Jap├│n"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-034', '┬┐Catar clasific├│ al Mundial 2026 en el grupoÔÇª?', '["B","A","H","K"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-grupos'),
('wc26-035', '┬┐Qu├® europeo est├í en el Grupo B junto a Canad├í?', '["Suiza","Suecia","Polonia","Serbia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-036', '┬┐Hait├¡ comparte grupo en 2026 con Brasil, Marruecos yÔÇª?', '["Escocia","Chile","Per├║","Costa Rica"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-037', '┬┐Escocia juega el Mundial 2026 en el grupo deÔÇª?', '["Brasil","Inglaterra","Alemania","Espa├▒a"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-038', '┬┐Marruecos repite grupo con Brasil en 2026 tras ser semifinalista enÔÇª?', '["2022","2018","2014","2010"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-039', '┬┐Estados Unidos comparte Grupo D con Paraguay, Australia yÔÇª?', '["Turqu├¡a","M├®xico","Canad├í","Colombia"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-040', '┬┐Paraguay est├í en el Grupo D junto al anfitri├│nÔÇª?', '["Estados Unidos","M├®xico","Canad├í","Brasil"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-041', '┬┐Australia juega en 2026 el grupo del anfitri├│nÔÇª?', '["Estados Unidos","Inglaterra","Francia","Alemania"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-042', '┬┐Curazao debuta en Mundiales en el Grupo E con Alemania yÔÇª?', '["Costa de Marfil y Ecuador","Francia y Senegal","Espa├▒a y Uruguay","Portugal y Colombia"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-grupos'),
('wc26-043', '┬┐Ecuador comparte grupo en 2026 con Alemania yÔÇª?', '["Curazao y Costa de Marfil","Jap├│n y Pa├¡ses Bajos","M├®xico y Sud├ífrica","Ghana e Inglaterra"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-044', '┬┐Alemania encabeza el GrupoÔÇª?', '["E","D","G","I"]'::jsonb, 0, 'easy', 2026, 'mundial-2026-grupos'),
('wc26-045', '┬┐Pa├¡ses Bajos comparte Grupo F con Jap├│n, Suecia yÔÇª?', '["T├║nez","Senegal","Marruecos","Ghana"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-046', '┬┐Jap├│n est├í en el Grupo F con Pa├¡ses Bajos yÔÇª?', '["Suecia y T├║nez","Corea del Sur y M├®xico","Ir├ín y Arabia Saud├¡","Qatar y Australia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-047', '┬┐Suecia clasific├│ al Mundial 2026 en el grupoÔÇª?', '["F","B","L","H"]'::jsonb, 0, 'hard', 2026, 'mundial-2026-grupos'),
('wc26-048', '┬┐B├®lgica encabeza el Grupo G con Egipto, Ir├ín yÔÇª?', '["Nueva Zelanda","Canad├í","Ghana","Arabia Saud├¡"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-049', '┬┐Ir├ín comparte grupo en 2026 con B├®lgica yÔÇª?', '["Egipto y Nueva Zelanda","Irak y Noruega","Qatar y Jordania","Turqu├¡a y Australia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-050', '┬┐Nueva Zelanda vuelve a un Mundial en el grupo deÔÇª?', '["B├®lgica","Argentina","Brasil","Francia"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos'),
('wc26-051', '┬┐Uruguay comparte Grupo H con Espa├▒a, Arabia Saudita yÔÇª?', '["Cabo Verde","Chile","Per├║","Paraguay"]'::jsonb, 0, 'medium', 2026, 'mundial-2026-grupos')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;
