insert into public.trivia_questions (id, question, options, correct_index, difficulty, world_cup_year, category)
values
('gol-012', '┬┐Qui├®n fue el m├íximo goleador del Mundial 1982?', '["Paolo Rossi","Karl-Heinz Rummenigge","Zico","Michel Platini"]'::jsonb, 0, 'medium', 1982, 'goleadores'),
('gol-013', '┬┐Cu├íntos goles marc├│ Paolo Rossi en Espa├▒a 1982?', '["6","5","7","8"]'::jsonb, 0, 'medium', 1982, 'goleadores'),
('gol-014', '┬┐Qui├®n fue el m├íximo goleador del Mundial 1994?', '["Hristo Stoichkov y Oleg Salenko (6)","Rom├írio","Roberto Baggio","Dennis Bergkamp"]'::jsonb, 0, 'hard', 1994, 'goleadores'),
('gol-015', '┬┐Qui├®n fue el m├íximo goleador del Mundial 1998?', '["Davor ┼áuker","Ronaldo","Dennis Bergkamp","Gabriel Batistuta"]'::jsonb, 0, 'medium', 1998, 'goleadores'),
('gol-016', '┬┐Cu├íntos goles marc├│ ┼áuker en Francia 1998?', '["6","5","7","8"]'::jsonb, 0, 'hard', 1998, 'goleadores'),
('gol-017', '┬┐Cu├íntos goles marc├│ Miroslav Klose como goleador del Mundial 2006?', '["5","6","4","7"]'::jsonb, 0, 'medium', 2006, 'goleadores'),
('gol-018', '┬┐Cu├íntos goles marc├│ Thomas M├╝ller en Sud├ífrica 2010?', '["5","4","6","7"]'::jsonb, 0, 'medium', 2010, 'goleadores'),
('gol-019', '┬┐Qui├®n fue el m├íximo goleador del Mundial 2010?', '["Diego Forl├ín, Wesley Sneijder, David Villa y Thomas M├╝ller (5)","Lionel Messi","David Villa solo","Diego Forl├ín solo"]'::jsonb, 0, 'hard', 2010, 'goleadores'),
('gol-020', '┬┐Cu├íntos goles marc├│ Mbapp├® en todo Qatar 2022?', '["8","6","7","9"]'::jsonb, 0, 'medium', 2022, 'goleadores'),
('gol-021', '┬┐Cu├íntos goles marc├│ Lionel Messi en Qatar 2022?', '["7","5","8","6"]'::jsonb, 0, 'medium', 2022, 'goleadores'),
('gol-022', '┬┐Cu├íntos goles marc├│ Juli├ín ├ülvarez en Qatar 2022?', '["4","3","5","6"]'::jsonb, 0, 'medium', 2022, 'goleadores'),
('gol-023', '┬┐Cu├íntos goles marc├│ Olivier Giroud en Qatar 2022?', '["4","3","5","2"]'::jsonb, 0, 'medium', 2022, 'goleadores'),
('gol-024', '┬┐Qui├®n tiene el r├®cord de m├ís goles en un solo Mundial (13)?', '["Just Fontaine","Miroslav Klose","Ronaldo","Gerd M├╝ller"]'::jsonb, 0, 'medium', 1958, 'goles-records'),
('gol-025', '┬┐En qu├® Mundial Fontaine marc├│ sus 13 goles?', '["1958","1962","1954","1966"]'::jsonb, 0, 'medium', 1958, 'goles-records'),
('gol-026', '┬┐Qui├®n super├│ a Ronaldo (15) como goleador hist├│rico en 2014?', '["Miroslav Klose","Lionel Messi","Thomas M├╝ller","Pel├®"]'::jsonb, 0, 'easy', 2014, 'goleadores'),
('gol-027', '┬┐En qu├® partido Klose igual├│ el r├®cord de Ronaldo y luego lo super├│?', '["Semifinal 2014 vs Brasil","Final 2014","Cuartos 2014","Grupos 2010"]'::jsonb, 0, 'hard', 2014, 'goleadores'),
('gol-028', '┬┐Cu├íntos goles marc├│ Pel├® en finales de Mundial?', '["3","2","4","5"]'::jsonb, 0, 'hard', null, 'goles-records'),
('gol-029', '┬┐Cu├íntos Mundiales distintos marc├│ gol Miroslav Klose?', '["4","3","5","2"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-030', '┬┐Cu├íntos Mundiales distintos marc├│ gol Lionel Messi?', '["5","4","3","6"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-031', '┬┐Cu├íntos goles marc├│ Cristiano Ronaldo en Mundiales (hasta 2022)?', '["8","7","9","10"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-032', '┬┐Cu├íntos goles marc├│ Kylian Mbapp├® en Mundiales (hasta 2022)?', '["12","10","8","14"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-033', '┬┐Qui├®n es el m├íximo goleador de Brasil en Mundiales?', '["Ronaldo con 15","Pel├®","Rom├írio","Neymar"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-034', '┬┐Cu├íntos goles mundialistas tiene Neymar (hasta 2022)?', '["8","10","6","7"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-035', '┬┐Cu├íntos goles marc├│ Diego Maradona en Mundiales?', '["8","10","6","12"]'::jsonb, 0, 'medium', null, 'goleadores'),
('gol-036', '┬┐Cu├íntos goles marc├│ Gabriel Batistuta en Mundiales?', '["10","8","12","6"]'::jsonb, 0, 'hard', null, 'goleadores'),
('gol-037', '┬┐Cu├íntos goles marc├│ J├╝rgen Klinsmann en Mundiales?', '["11","9","13","8"]'::jsonb, 0, 'hard', null, 'goleadores'),
('gol-038', '┬┐Cu├íntos goles marc├│ Te├│filo Cubillas en Mundiales?', '["10","8","12","6"]'::jsonb, 0, 'hard', null, 'goleadores'),
('gol-039', '┬┐Qui├®n marc├│ 5 goles en un partido del Mundial 1994?', '["Oleg Salenko","Rom├írio","Hristo Stoichkov","Dennis Bergkamp"]'::jsonb, 0, 'medium', 1994, 'goles-records'),
('gol-040', '┬┐Contra qu├® selecci├│n Salenko marc├│ 5 goles en 1994?', '["Camer├║n","M├®xico","Suecia","Colombia"]'::jsonb, 0, 'hard', 1994, 'goles-records'),
('gol-041', '┬┐Cu├íl es el resultado m├ís abultado en un Mundial?', '["Hungria 10-1 El Salvador (1982)","Alemania 8-0 Arabia Saudita","Yugoslavia 9-0 Zaire","Uruguay 7-0 Escocia"]'::jsonb, 0, 'hard', 1982, 'goles-records'),
('gol-042', '┬┐Geoff Hurst marc├│ un hat-trick en la final deÔÇª?', '["1966","1970","1962","1974"]'::jsonb, 0, 'easy', 1966, 'goles-finales'),
('gol-043', '┬┐Antes de Mbapp├® en 2022, ┬┐qui├®n hab├¡a hecho hat-trick en una final?', '["Geoff Hurst (1966)","Pel├®","Ronaldo","Zidane"]'::jsonb, 0, 'medium', 2022, 'goles-finales'),
('gol-044', '┬┐Mbapp├® anot├│ 3 goles en la final 2022 peroÔÇª?', '["Francia igual perdi├│ en penales","Francia gan├│","Fue expulsado","No hubo pr├│rroga"]'::jsonb, 0, 'easy', 2022, 'goles-finales'),
('gol-045', '┬┐Cu├íntos goles marc├│ Rusia (URSS) en el partido vs Camer├║n en 1994?', '["6","5","7","4"]'::jsonb, 0, 'hard', 1994, 'goles-records'),
('gol-046', '┬┐Alemania marc├│ 7 goles contra Brasil en semifinales deÔÇª?', '["2014","2010","2018","2002"]'::jsonb, 0, 'easy', 2014, 'goles-records'),
('gol-047', '┬┐Espa├▒a marc├│ 7-0 a Costa Rica en el MundialÔÇª?', '["2022","2010","2014","2018"]'::jsonb, 0, 'easy', 2022, 'goles-records'),
('gol-048', '┬┐Qui├®n marc├│ dos goles en la final de 1978 para Argentina?', '["Mario Kempes","Leopoldo Luque","Daniel Passarella","Daniel Bertoni"]'::jsonb, 0, 'hard', 1978, 'goles-finales'),
('gol-049', '┬┐Cu├íl es el gol m├ís r├ípido en la historia del Mundial?', '["Hakan ┼×├╝k├╝r (~11 segundos)","Clint Dempsey (~29 seg)","Bryan Robson (~27 seg)","Emile Mpenza (~20 seg)"]'::jsonb, 0, 'hard', 2002, 'goles-minutos'),
('gol-050', '┬┐┼×├╝k├╝r marc├│ el gol m├ís r├ípido en 2002 contraÔÇª?', '["Corea del Sur","Turqu├¡a no ÔÇö Turqu├¡a marc├│","Brasil","Senegal"]'::jsonb, 0, 'hard', 2002, 'goles-minutos'),
('gol-051', '┬┐Clint Dempsey marc├│ el gol m├ís r├ípido de USA en 2014 al minutoÔÇª?', '["29 segundos","11 segundos","45 segundos","2 minutos"]'::jsonb, 0, 'hard', 2014, 'goles-minutos')
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index,
  difficulty = excluded.difficulty,
  world_cup_year = excluded.world_cup_year,
  category = excluded.category;
