import type { TriviaQuestionSeed } from './constants'

function q(
  id: string,
  question: string,
  correct: string,
  wrong: [string, string, string],
  difficulty: 'easy' | 'medium' | 'hard',
  category: string,
  worldCupYear?: number,
): TriviaQuestionSeed {
  const options = [correct, wrong[0], wrong[1], wrong[2]] as [string, string, string, string]
  return { id, question, options, correctIndex: 0, difficulty, category, worldCupYear }
}

/** +100 preguntas revisadas (Mundiales + Mundial 2026). */
export const TRIVIA_QUESTIONS_EXTRA: TriviaQuestionSeed[] = [
  q('z-001', '¿Qué países organizarán el Mundial 2026?', 'Estados Unidos, México y Canadá', ['Brasil, Argentina y Chile', 'España, Portugal e Italia', 'Qatar, Emiratos y Arabia Saudita'], 'easy', 'mundial-2026', 2026),
  q('z-002', '¿Cuántos equipos participarán en el Mundial 2026?', '48', ['32', '40', '36'], 'easy', 'mundial-2026', 2026),
  q('z-003', '¿Cuántos partidos oficiales habrá en el Mundial 2026?', '104', ['96', '112', '88'], 'medium', 'mundial-2026', 2026),
  q('z-004', '¿Cuántos grupos tendrá la fase de grupos del Mundial 2026?', '12', ['8', '16', '10'], 'medium', 'mundial-2026', 2026),
  q('z-005', '¿Dónde se jugará la final del Mundial 2026?', 'MetLife Stadium (NY/NJ)', ['Estadio Azteca', 'Rose Bowl', 'Hard Rock Stadium'], 'medium', 'mundial-2026', 2026),
  q('z-006', '¿Qué selección abre el Mundial 2026 en el Estadio Ciudad de México?', 'México', ['Estados Unidos', 'Canadá', 'Brasil'], 'easy', 'mundial-2026', 2026),
  q('z-007', '¿Contra qué rival debuta México en el Mundial 2026?', 'Sudáfrica', ['Corea del Sur', 'República Checa', 'Marruecos'], 'easy', 'mundial-2026', 2026),
  q('z-008', '¿En qué grupo está Argentina en el Mundial 2026?', 'Grupo J', ['Grupo A', 'Grupo C', 'Grupo H'], 'medium', 'mundial-2026', 2026),
  q('z-009', '¿Contra quién debuta Argentina en el Mundial 2026?', 'Argelia', ['Austria', 'Jordania', 'Marruecos'], 'medium', 'mundial-2026', 2026),
  q('z-010', '¿Qué otro equipo europeo comparte grupo con Argentina en 2026?', 'Austria', ['Alemania', 'Croacia', 'Suiza'], 'medium', 'mundial-2026', 2026),
  q('z-011', '¿Brasil comparte grupo en 2026 con Marruecos y…?', 'Haití y Escocia', ['Japón y Senegal', 'Uruguay y Corea del Sur', 'España y Costa Rica'], 'hard', 'mundial-2026', 2026),
  q('z-012', '¿Estados Unidos comparte grupo con Paraguay y…?', 'Australia y Turquía', ['México y Canadá', 'Ghana y Ecuador', 'Catar y Suiza'], 'hard', 'mundial-2026', 2026),
  q('z-013', '¿España comparte grupo en 2026 con Arabia Saudita y…?', 'Cabo Verde y Uruguay', ['Chile y Perú', 'Nigeria y Camerún', 'Polonia y Dinamarca'], 'hard', 'mundial-2026', 2026),
  q('z-014', '¿Francia comparte grupo en 2026 con Senegal y…?', 'Irak y Noruega', ['Marruecos y Croacia', 'Túnez y Ghana', 'Bélgica y Suiza'], 'hard', 'mundial-2026', 2026),
  q('z-015', '¿Inglaterra comparte grupo en 2026 con Ghana y…?', 'Panamá y Croacia', ['Gales y Serbia', 'Dinamarca y Eslovenia', 'Irán y EE.UU.'], 'hard', 'mundial-2026', 2026),
  q('z-016', '¿Alemania comparte grupo en 2026 con Ecuador y…?', 'Costa de Marfil y Curazao', ['Polonia y Suecia', 'Serbia y Suiza', 'Japón y Australia'], 'hard', 'mundial-2026', 2026),
  q('z-017', '¿Portugal comparte grupo en 2026 con Colombia y…?', 'República Democrática del Congo y Uzbekistán', ['Brasil y Serbia', 'Uruguay y Ghana', 'Croacia y Marruecos'], 'hard', 'mundial-2026', 2026),
  q('z-018', '¿Cuántas sedes tendrá el Mundial 2026?', '16', ['12', '20', '14'], 'medium', 'mundial-2026', 2026),
  q('z-019', '¿Qué ciudad canadiense será sede en 2026?', 'Toronto y Vancouver', ['Montreal solamente', 'Ottawa y Calgary', 'Quebec y Winnipeg'], 'hard', 'mundial-2026', 2026),
  q('z-020', '¿El Mundial 2026 será el primero con cuántos equipos?', '48', ['40', '36', '32'], 'easy', 'mundial-2026', 2026),
  q('z-021', '¿Quién fue el máximo goleador del Mundial 1978?', 'Mario Kempes', ['Paolo Rossi', 'Teófilo Cubillas', 'Rob Rensenbrink'], 'hard', 'goleadores', 1978),
  q('z-022', '¿Quién fue el máximo goleador del Mundial 1986 con 6 goles?', 'Gary Lineker', ['Diego Maradona', 'Emilio Butragueño', 'Careca'], 'medium', 'goleadores', 1986),
  q('z-023', '¿Quién fue el máximo goleador del Mundial 1990?', 'Salvatore Schillaci', ['Roger Milla', 'Lothar Matthäus', 'Tomáš Skuhravý'], 'medium', 'goleadores', 1990),
  q('z-024', '¿Cuántos goles marcó Romário en el Mundial 1994?', '5', ['6', '4', '7'], 'hard', 'goleadores', 1994),
  q('z-025', '¿Oleg Salenko marcó cuántos goles en un partido en 1994?', '5', ['4', '6', '3'], 'hard', 'records', 1994),
  q('z-026', '¿Qué selección anfitriona perdió 7-1 en semifinales en 2014?', 'Brasil', ['Sudáfrica', 'Alemania', 'Rusia'], 'easy', 'momentos', 2014),
  q('z-027', '¿Quién marcó el gol del 1-0 en la final de 2010 para España?', 'Andrés Iniesta', ['David Villa', 'Carlos Puyol', 'Fernando Torres'], 'easy', 'finales', 2010),
  q('z-028', '¿Quién marcó el gol de la victoria en la final de 2014?', 'Mario Götze', ['André Schürrle', 'Miroslav Klose', 'Thomas Müller'], 'medium', 'finales', 2014),
  q('z-029', '¿Quién marcó el tercer gol de Francia en la final 2022?', 'Kylian Mbappé', ['Olivier Giroud', 'Antoine Griezmann', 'Kingsley Coman'], 'medium', 'finales', 2022),
  q('z-030', '¿Qué arquero atajó dos penales en la final 2022?', 'Emiliano Martínez', ['Hugo Lloris', 'Alisson', 'Courtois'], 'easy', 'leyendas', 2022),
  q('z-031', '¿En qué Mundial Pelé marcó un hat-trick en semifinales?', '1958', ['1962', '1970', '1966'], 'hard', 'leyendas', 1958),
  q('z-032', '¿Roger Milla celebró en qué Mundial siendo veterano camerunés?', '1990', ['1994', '1986', '1982'], 'medium', 'leyendas', 1990),
  q('z-033', '¿Cuántos Mundiales ganó Franz Beckenbauer como jugador?', '1', ['2', '3', '0'], 'hard', 'leyendas', 1974),
  q('z-034', '¿Paolo Rossi fue goleador y campeón en…?', '1982', ['1978', '1986', '1990'], 'medium', 'leyendas', 1982),
  q('z-035', '¿Zinedine Zidane anotó dos goles de cabeza en la final de…?', '1998', ['2006', '2002', '2010'], 'easy', 'leyendas', 1998),
  q('z-036', '¿Cuántos goles marcó Just Fontaine en el Mundial 1958?', '13', ['10', '11', '15'], 'hard', 'records', 1958),
  q('z-037', '¿Qué país fue tercero en el Mundial 1930?', 'Estados Unidos', ['Yugoslavia', 'Argentina', 'Brasil'], 'hard', 'records', 1930),
  q('z-038', '¿Qué selección ganó el Mundial 1938 siendo campeón defensor?', 'Italia', ['Brasil', 'Hungría', 'Francia'], 'hard', 'campeones', 1938),
  q('z-039', '¿Qué país organizó el Mundial 1958?', 'Suecia', ['Suiza', 'Noruega', 'Dinamarca'], 'medium', 'sedes', 1958),
  q('z-040', '¿Qué país organizó el Mundial 1962?', 'Chile', ['Argentina', 'Perú', 'Uruguay'], 'medium', 'sedes', 1962),
  q('z-041', '¿Qué país organizó el Mundial 1970?', 'México', ['Estados Unidos', 'Colombia', 'Brasil'], 'easy', 'sedes', 1970),
  q('z-042', '¿Qué país organizó el Mundial 1982?', 'España', ['Portugal', 'Italia', 'Francia'], 'medium', 'sedes', 1982),
  q('z-043', '¿Qué país organizó el Mundial 1990?', 'Italia', ['Alemania', 'Francia', 'España'], 'medium', 'sedes', 1990),
  q('z-044', '¿Qué país organizó el Mundial 2014?', 'Brasil', ['Argentina', 'Chile', 'Colombia'], 'easy', 'sedes', 2014),
  q('z-045', '¿Qué país organizó el Mundial 2018?', 'Rusia', ['Ucrania', 'Polonia', 'Turquía'], 'easy', 'sedes', 2018),
  q('z-046', '¿Cuántos títulos mundiales tiene Uruguay?', '2', ['3', '1', '4'], 'medium', 'campeones'),
  q('z-047', '¿Cuántos títulos mundiales tiene Francia?', '2', ['1', '3', '4'], 'medium', 'campeones'),
  q('z-048', '¿Cuántos títulos mundiales tiene España?', '1', ['2', '0', '3'], 'easy', 'campeones'),
  q('z-049', '¿Cuántos títulos mundiales tiene Inglaterra?', '1', ['2', '0', '3'], 'easy', 'campeones'),
  q('z-050', '¿Qué selección fue subcampeona en 1978?', 'Países Bajos', ['Brasil', 'Italia', 'Alemania'], 'medium', 'finales', 1978),
  q('z-051', '¿Qué selección fue subcampeona en 1982?', 'Alemania', ['Francia', 'Polonia', 'Italia'], 'medium', 'finales', 1982),
  q('z-052', '¿Qué selección fue subcampeona en 1990?', 'Argentina', ['Italia', 'Inglaterra', 'Alemania'], 'medium', 'finales', 1990),
  q('z-053', '¿Qué selección fue subcampeona en 2002?', 'Alemania', ['Brasil', 'Turquía', 'Corea del Sur'], 'medium', 'finales', 2002),
  q('z-054', '¿Qué selección fue subcampeona en 2014?', 'Argentina', ['Brasil', 'Países Bajos', 'Alemania'], 'easy', 'finales', 2014),
  q('z-055', '¿Qué selección terminó tercera en 2022?', 'Croacia', ['Marruecos', 'Brasil', 'Países Bajos'], 'medium', 'records', 2022),
  q('z-056', '¿Qué selección terminó cuarta en 2022?', 'Marruecos', ['Croacia', 'Inglaterra', 'Portugal'], 'medium', 'records', 2022),
  q('z-057', '¿Qué selección fue cuarta en el Mundial 2010?', 'Uruguay', ['Alemania', 'España', 'Ghana'], 'medium', 'records', 2010),
  q('z-058', '¿Senegal venció al campeón defensor en el debut de 2002 a…?', 'Francia', ['Brasil', 'Italia', 'Alemania'], 'medium', 'momentos', 2002),
  q('z-059', '¿Italia campeona defensora quedó eliminada en grupos en…?', '2010', ['2006', '2014', '2018'], 'medium', 'momentos', 2010),
  q('z-060', '¿España campeona defensora quedó eliminada en grupos en…?', '2014', ['2010', '2018', '2022'], 'medium', 'momentos', 2014),
  q('z-061', '¿Alemania campeona defensora quedó eliminada en grupos en…?', '2018', ['2014', '2022', '2010'], 'medium', 'momentos', 2018),
  q('z-062', '¿Francia campeona defensora quedó eliminada en grupos en…?', '2002', ['1998', '2006', '2010'], 'hard', 'momentos', 2002),
  q('z-063', '¿El VAR se usó ampliamente por primera vez en…?', '2018', ['2014', '2022', '2010'], 'easy', 'formato', 2018),
  q('z-064', '¿Cuántos equipos participaron en el Mundial 1986?', '24', ['16', '32', '20'], 'hard', 'formato', 1986),
  q('z-065', '¿Cuántos equipos participaron en el Mundial 1998?', '32', ['24', '48', '16'], 'medium', 'formato', 1998),
  q('z-066', '¿El sistema de 32 equipos comenzó en el Mundial de…?', '1998', ['1994', '2002', '1986'], 'medium', 'formato', 1998),
  q('z-067', '¿Cuántos partidos juega el campeón en un Mundial de 32 equipos?', '7', ['6', '8', '5'], 'hard', 'formato'),
  q('z-068', '¿Qué balón se usó en el Mundial 2010?', 'Jabulani', ['Teamgeist', 'Brazuca', 'Telstar 18'], 'medium', 'curiosidades', 2010),
  q('z-069', '¿Qué balón se usó en el Mundial 2014?', 'Brazuca', ['Jabulani', 'Al Rihla', 'Telstar 18'], 'easy', 'curiosidades', 2014),
  q('z-070', '¿Qué balón se usó en el Mundial 2018?', 'Telstar 18', ['Brazuca', 'Al Rihla', 'Teamgeist'], 'medium', 'curiosidades', 2018),
  q('z-071', '¿Qué balón se usó en el Mundial 2022?', 'Al Rihla', ['Telstar 18', 'Brazuca', 'Jabulani'], 'easy', 'curiosidades', 2022),
  q('z-072', '¿La mascota del Mundial 2014 era…?', 'Fuleco', ['Zabivaka', 'Zakumi', 'La\'eeb'], 'medium', 'curiosidades', 2014),
  q('z-073', '¿La mascota del Mundial 2018 era…?', 'Zabivaka', ['Fuleco', 'La\'eeb', 'World Cup Willie'], 'medium', 'curiosidades', 2018),
  q('z-074', '¿La mascota del Mundial 2022 era…?', 'La\'eeb', ['Zabivaka', 'Zakumi', 'Fuleco'], 'easy', 'curiosidades', 2022),
  q('z-075', '¿La mascota del Mundial 2010 era…?', 'Zakumi', ['Fuleco', 'Zabivaka', 'Striker'], 'medium', 'curiosidades', 2010),
  q('z-076', '¿Qué estadio albergó la final de 1950?', 'Maracaná', ['Azteca', 'Wembley', 'Centenario'], 'hard', 'sedes', 1950),
  q('z-077', '¿Qué estadio albergó la final de 2014?', 'Maracaná', ['Mineirão', 'Arena Corinthians', 'Castelão'], 'medium', 'sedes', 2014),
  q('z-078', '¿Qué estadio albergó la final de 2022?', 'Lusail', ['Al Bayt', '974', 'Education City'], 'medium', 'sedes', 2022),
  q('z-079', '¿El Estadio Azteca albergó finales en…?', '1970 y 1986', ['1986 solamente', '1994', '1970 solamente'], 'hard', 'sedes'),
  q('z-080', '¿Quién fue DT de Argentina campeona en 1978?', 'César Luis Menotti', ['Carlos Bilardo', 'Alfio Basile', 'Marcelo Bielsa'], 'hard', 'dt', 1978),
  q('z-081', '¿Quién fue DT de Argentina campeona en 1986?', 'Carlos Bilardo', ['Menotti', 'Sabella', 'Scaloni'], 'medium', 'dt', 1986),
  q('z-082', '¿Quién fue DT de Brasil campeona en 2002?', 'Luiz Felipe Scolari', ['Zagallo', 'Parreira', 'Tite'], 'medium', 'dt', 2002),
  q('z-083', '¿Quién fue DT de Francia campeona en 2018?', 'Didier Deschamps', ['Domenech', 'Blanc', 'Lemerre'], 'medium', 'dt', 2018),
  q('z-084', '¿Quién fue DT de España campeona en 2010?', 'Vicente del Bosque', ['Aragonés', 'Lopetegui', 'Enrique'], 'easy', 'dt', 2010),
  q('z-085', '¿Cuántos goles marcó Lionel Messi en Mundiales (hasta 2022)?', '13', ['10', '15', '11'], 'hard', 'leyendas'),
  q('z-086', '¿Cristiano Ronaldo marcó gol en cinco Mundiales distintos?', 'Sí', ['No', 'Solo en cuatro', 'Solo en tres'], 'medium', 'leyendas'),
  q('z-087', '¿Lionel Messi ganó el Balón de Oro del torneo en…?', '2022', ['2014', '2018', '2010'], 'easy', 'leyendas', 2022),
  q('z-088', '¿Luka Modrić ganó el Balón de Oro del torneo en…?', '2018', ['2022', '2014', '2010'], 'medium', 'leyendas', 2018),
  q('z-089', '¿Diego Maradona levantó la Copa en…?', '1986', ['1982', '1990', '1978'], 'easy', 'leyendas', 1986),
  q('z-090', '¿Pelé ganó su primer Mundial con…?', '17 años', ['19 años', '21 años', '15 años'], 'medium', 'leyendas', 1958),
  q('z-091', '¿Qué país eliminó a Argentina en el Mundial 2010?', 'Alemania', ['España', 'Brasil', 'Uruguay'], 'medium', 'momentos', 2010),
  q('z-092', '¿Qué país eliminó a Argentina en el Mundial 2014 en la final?', 'Alemania', ['Brasil', 'Holanda', 'Bélgica'], 'easy', 'momentos', 2014),
  q('z-093', '¿Qué país eliminó a Brasil en cuartos en 2018?', 'Bélgica', ['Francia', 'Croacia', 'México'], 'medium', 'momentos', 2018),
  q('z-094', '¿Qué país eliminó a España en octavos en 2022?', 'Marruecos', ['Croacia', 'Brasil', 'Alemania'], 'medium', 'momentos', 2022),
  q('z-095', '¿Corea del Sur llegó a semifinales en casa en…?', '2002', ['2010', '2006', '2018'], 'medium', 'records', 2002),
  q('z-096', '¿Turquía terminó tercera en el Mundial…?', '2002', ['2006', '2010', '1998'], 'hard', 'records', 2002),
  q('z-097', '¿Cuántas selecciones diferentes han ganado el Mundial?', '8', ['10', '6', '12'], 'hard', 'records'),
  q('z-098', '¿Los Mundiales de 1942 y 1946 no se jugaron por…?', 'La Segunda Guerra Mundial', ['Conflictos comerciales', 'Un boicot olímpico', 'Una epidemia global'], 'easy', 'historia'),
  q('z-099', '¿El trofeo original entregado hasta 1970 se llama…?', 'Copa Jules Rimet', ['Copa FIFA', 'Copa Golden Ball', 'Copa Del Mundo'], 'hard', 'curiosidades'),
  q('z-100', '¿Brasil se quedó permanentemente con la Copa Jules Rimet al ganar su…?', 'Tercer título (1970)', ['Quinto título (2002)', 'Primer título (1958)', 'Segundo título (1962)'], 'hard', 'curiosidades', 1970),
]
